from django.core.management.base import BaseCommand
from base.models import Spell, SpellcastingClass

class Command(BaseCommand):
    help = 'Populate database with D&D 5e spells'

    def handle(self, *args, **options):
        # Create SpellcastingClass instances
        classes = [
            'Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 
            'Sorcerer', 'Warlock', 'Wizard'
        ]
        
        class_objs = {}
        for class_name in classes:
            obj, created = SpellcastingClass.objects.get_or_create(name=class_name)
            class_objs[class_name] = obj
            if created:
                self.stdout.write(f"Created class: {class_name}")

        # Parse and add spells
        spells_data = [
            # CANTRIPS (Level 0)
            ('Acid Splash', 0, 'Conj', 'A', 'V/S', False, False, 'I', '60\'',
             '1d6 acid damage against up to two adjacent targets, Dex saves.', ['Sorcerer', 'Wizard']),
            ('Blade Ward', 0, 'Abj', 'A', 'V/S', False, False, '1r', 'S', 
             'Resistance to bludgeoning, piercing, slashing until your next turn.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Chill Touch', 0, 'Necro', 'A', 'V/S', False, False, '1r', '120\'',
             'Target takes 1d8 necrotic damage and can\'t heal until your next turn.', ['Sorcerer', 'Warlock', 'Wizard']),
            ('Dancing Lights', 0, 'Evo', 'A', 'V/S/M', True, False, '1m', '120\'',
             'Creates four torch-sized lights, which illuminate 10\' and can be moved 60\' as a bonus action.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Druidcraft', 0, 'Trans', 'A', 'V/S', False, False, 'I', '30\'',
             'Cause one of several minor nature-related effects.', ['Druid']),
            ('Eldritch Blast', 0, 'Evo', 'A', 'V/S', False, False, 'I', '120\'',
             'Deals 1d10 force damage to target. More attacks at higher caster levels.', ['Warlock']),
            ('Fire Bolt', 0, 'Evo', 'A', 'V/S', False, False, 'I', '120\'',
             'Target takes 1d10 fire damage. Damage increases at higher caster levels.', ['Sorcerer', 'Wizard']),
            ('Friends', 0, 'Ench', 'A', 'S/M', True, False, '1m', 'S',
             'Grants advantage on Cha checks against target, but at the end, the creature knows you used magic on it and becomes hostile.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Guidance', 0, 'Div', 'A', 'V/S', True, False, '1m', 'T',
             'Target can roll 1d4 and add it to a single ability check.', ['Cleric', 'Druid']),
            ('Light', 0, 'Evo', 'A', 'V/M', False, False, '1h', 'T',
             'Object sheds 20\' of bright light and an additional 20\' of dim light.', ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Wizard']),
            ('Mage Hand', 0, 'Conj', 'A', 'V/S', False, False, '1m', '30\'',
             'Creates spectral hand that can lift 10lbs.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Mending', 0, 'Trans', 'L', 'V/S/M', False, False, 'I', 'T',
             'Repairs a single break or tear in the touched object.', ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Wizard']),
            ('Message', 0, 'Trans', 'A', 'V/S/M', False, False, '1r', '120\'',
             'Sends a whispered message to a target which only they can hear.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Minor Illusion', 0, 'Ill', 'A', 'S/M', False, False, '1m', '30\'',
             'Creates an auditory or visual hallucination.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Poison Spray', 0, 'Conj', 'A', 'V/S', False, False, 'I', '10\'',
             'Target takes 1d12 poison damage, Con save prevents.', ['Druid', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Prestidigitation', 0, 'Trans', 'A', 'V/S', False, False, 'Sp', '10\'',
             'Creates minor practical effects.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Produce Flames', 0, 'Conj', 'A', 'V/S', False, False, '10m', 'S',
             'Ranged spell attack within 30\' deals 1d8 fire damage.', ['Druid']),
            ('Ray of Frost', 0, 'Evo', 'A', 'V/S', False, False, 'I', '60\'',
             'Target takes 1d8 cold damage and loses 10\' of move speed for a turn.', ['Sorcerer', 'Wizard']),
            ('Resistance', 0, 'Abj', 'A', 'V/S/M', True, False, '1m', 'T',
             'Lets the target creature add +1d4 to a save.', ['Cleric', 'Druid']),
            ('Sacred Flame', 0, 'Evo', 'A', 'V/S', False, False, 'I', '60\'',
             '1d8 radiant damage, Dex save stops.', ['Cleric']),
            ('Shillelagh', 0, 'Trans', 'BA', 'V/S/M', False, False, '1m', 'T',
             'Held club or quarterstaff uses spellcasting ability.', ['Druid']),
            ('Shocking Grasp', 0, 'Evo', 'A', 'V/S', False, False, 'I', 'T',
             'Target takes 1d8 lightning damage, and can\'t take reactions.', ['Sorcerer', 'Wizard']),
            ('Spare the Dying', 0, 'Necro', 'A', 'V/S', False, False, 'I', 'T',
             'Target creature at 0 hp is stabilized.', ['Cleric']),
            ('Thaumaturgy', 0, 'Trans', 'A', 'V', False, False, '1m', '30\'',
             'Manifest a minor effect that is suggestive of supernatural power.', ['Cleric']),
            ('Thorn Whip', 0, 'Trans', 'A', 'V/S/M', False, False, 'I', '30\'',
             'Melee spell attack deals 1d6 piercing damage and pulls target.', ['Druid']),
            ('True Strike', 0, 'Div', 'A', 'S', True, False, '1r', '30\'',
             'Grants advantage on an attack roll against chosen creature next round.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Vicious Mockery', 0, 'Ench', 'A', 'V', False, False, 'I', '60\'',
             'Target takes 1d4 psychic and has disadvantage on next attack roll.', ['Bard']),

            # 1ST LEVEL SPELLS
            ('Alarm', 1, 'Abj', 'L', 'V/S/M', False, True, '8h', '30\'',
             'Sets an alarm which pings you if you\'re within a mile when something passes through the marked area.', ['Ranger', 'Wizard']),
            ('Animal Friendship', 1, 'Ench', 'A', 'V/S/M', False, False, '24h', '30\'',
             'Charms a beast with <3 Int for the day.', ['Bard', 'Druid', 'Ranger']),
            ('Armor of Agathys', 1, 'Abj', 'A', 'V/S/M', False, False, '1h', 'S',
             'You gain 5 temporary hit points, and whenever a creature hits you with a melee attack while you have temp HP remaining, the attacker takes 5 cold damage.', ['Warlock']),
            ('Bane', 1, 'Ench', 'A', 'V/S/M', True, False, '1m', '30\'',
             'Up to three creatures must make a Cha save or suffer a 1d4 penalty each time they attack or save.', ['Bard', 'Cleric']),
            ('Bless', 1, 'Ench', 'A', 'V/S/M', True, False, '1m', '30\'',
             'Target adds 1d4 to all attack rolls and saves.', ['Cleric', 'Paladin']),
            ('Burning Hands', 1, 'Evo', 'A', 'V/S', False, False, 'I', 'S',
             '3d6 fire damage to creatures in 15\' cone. Dex save halves damage.', ['Sorcerer', 'Wizard']),
            ('Charm Person', 1, 'Ench', 'A', 'V/S', False, False, '1h', '30\'',
             'Wis save or target is charmed.', ['Bard', 'Druid', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Color Spray', 1, 'Ill', 'A', 'V/S', False, False, 'I', 'S',
             'Spray of colors blinds, stuns, or knocks unconscious creatures in a 15\' cone.', ['Sorcerer', 'Wizard']),
            ('Command', 1, 'Ench', 'A', 'V', False, False, '1r', '60\'',
             'Issue a one word command. Wisdom save counters.', ['Cleric', 'Paladin']),
            ('Compelled Duel', 1, 'Ench', 'BA', 'V', True, False, '1m', '30\'',
             'Target must make Wis save or be compelled to fight you.', ['Paladin']),
            ('Comprehend Languages', 1, 'Div', 'A', 'V/S/M', False, True, '1h', 'S',
             'Allows you to understand any spoken or written language for an hour.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Cure Wounds', 1, 'Evo', 'A', 'V/S', False, False, 'I', 'T',
             'Heals 1d8 + (spellcasting ability modifier) damage.', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger']),
            ('Detect Evil or Good', 1, 'Div', 'A', 'V/S', True, False, '10m', 'S',
             'Recognizes aberration, celestial, fey, fiend, or undead within 30\'.', ['Cleric', 'Paladin']),
            ('Detect Magic', 1, 'Div', 'A', 'V/S', True, True, '10m', 'S',
             'Senses magical objects or creatures within 30\'.', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Detect Poison and Disease', 1, 'Div', 'A', 'V/S/M', True, True, '10m', 'S',
             'Senses poison, poisonous creatures, and disease within 30\'.', ['Cleric', 'Druid', 'Paladin', 'Ranger']),
            ('Disguise Self', 1, 'Ill', 'A', 'V/S', False, False, '1h', 'S',
             'Makes you and your armor look like another person.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Dissonant Whispers', 1, 'Ench', 'A', 'V', False, False, 'I', '60\'',
             '3d6 psychic damage, and target must use reaction to flee you.', ['Bard']),
            ('Divine Favor', 1, 'Evo', 'BA', 'V/S', True, False, '1m', 'S',
             'Weapon deals +1d4 radiant damage.', ['Paladin']),
            ('Ensnaring Strike', 1, 'Conj', 'BA', 'V', True, False, '1m', 'S',
             'When you next hit an opponent with your weapon, target is restrained by vines.', ['Ranger']),
            ('Faerie Fire', 1, 'Evo', 'A', 'V', True, False, '1m', '60\'',
             'Objects and people in a 20\' cube are lit up, counteracting invisibility.', ['Bard', 'Druid']),
            ('Feather Fall', 1, 'Trans', 'RA', 'V/M', False, False, '1m', '60\'',
             'Up to five falling creatures have their descent velocity capped at 60\'/round.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Find Familiar', 1, 'Conj', 'L', 'V/S/M', False, True, 'I', '10\'',
             'Gain a companion spirit in animal form to assist your magic.', ['Wizard', 'Warlock']),
            ('Fog Cloud', 1, 'Conj', 'A', 'V/S', True, False, '1h', '120\'',
             '20\' fog heavily obscures area.', ['Bard', 'Druid', 'Ranger', 'Sorcerer', 'Wizard']),
            ('Goodberry', 1, 'Trans', 'A', 'V/S/M', False, False, 'I', 'T',
             'Creates ten magic berries that each heal 1 hit point.', ['Druid', 'Ranger']),
            ('Guiding Bolt', 1, 'Evo', 'A', 'V/S', False, False, '1r', '120\'',
             'Ranged spell attack deals 4d6 radiant damage.', ['Cleric']),
            ('Hail of Thorns', 1, 'Conj', 'BA', 'V', True, False, '1m', 'S',
             'Around next creature struck with ranged weapon attack, deal 1d10 pierce to target and all within 5\'.', ['Ranger']),
            ('Healing Word', 1, 'Evo', 'BA', 'V', False, False, 'I', '60\'',
             'Creature regains 1d4 + (spellcasting ability mod) HP.', ['Bard', 'Cleric', 'Druid', 'Paladin']),
            ('Heroism', 1, 'Ench', 'A', 'V/S', True, False, '1m', 'T',
             'Creature gains immunity to being frightened and gains temporary hit points.', ['Bard', 'Paladin']),
            ('Hunter\'s Mark', 1, 'Div', 'BA', 'V', True, False, '1h', '90\'',
             'Marks target, granting +1d6 damage and advantage to Perception and Survival checks.', ['Ranger']),
            ('Identify', 1, 'Div', 'L', 'V/S/M*', False, True, 'I', 'T',
             'Identifies what a magical item does.', ['Bard', 'Wizard']),
            ('Jump', 1, 'Trans', 'A', 'V/S/M', False, False, '1m', 'T',
             'Triples target\'s jump distance.', ['Bard', 'Druid', 'Ranger', 'Sorcerer', 'Wizard']),
            ('Longstrider', 1, 'Trans', 'A', 'V/S/M', False, False, '1h', 'T',
             'Target\'s speed increases by +10\'.', ['Bard', 'Druid', 'Ranger', 'Wizard']),
            ('Magic Missile', 1, 'Evo', 'A', 'V/S', False, False, 'I', '120\'',
             'Shoot magic darts at one creature or several. Each deals 1d4 + 1 force damage.', ['Sorcerer', 'Wizard']),
            ('Protection from Evil and Good', 1, 'Abj', 'A', 'V/S/M', True, False, '10m', 'T',
             'Until the spell ends, one willing creature you touch is protected against certain creature types.', ['Cleric', 'Paladin', 'Warlock', 'Wizard']),
            ('Searing Smite', 1, 'Evo', 'BA', 'V', True, False, '1m', 'S',
             'Adds 1d6 fire damage to next melee weapon attack.', ['Paladin']),
            ('Shield', 1, 'Abj', 'RA', 'V/S', False, False, '1r', 'S',
             'Gain +5 AC including against the triggering attack.', ['Sorcerer', 'Wizard']),
            ('Shield of Faith', 1, 'Abj', 'BA', 'V/S/M', True, False, '10m', '60\'',
             'Grants +2 AC to target for duration.', ['Cleric', 'Paladin']),
            ('Silent Image', 1, 'Ill', 'A', 'V/S/M', True, False, '10m', '60\'',
             'Creates a visual illusion that you can move.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Sleep', 1, 'Ench', 'A', 'V/S/M', False, False, '1m', '90\'',
             '5d8 hit points of creatures are put to sleep.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Speak with Animals', 1, 'Div', 'A', 'V/S', False, True, '10m', 'S',
             'You can speak and verbally communicate with beasts for the duration.', ['Bard', 'Druid', 'Ranger']),
            ('Tasha\'s Hideous Laughter', 1, 'Ench', 'A', 'V/S/M', True, False, '1m', '60\'',
             'Target must succeed on Wis save or fall prone laughing.', ['Bard', 'Wizard']),
            ('Thunderous Smite', 1, 'Evo', 'BA', 'V', True, False, '1m', 'S',
             'Next attack deals 2d6 thunder damage to the target and pushes it 10\' away.', ['Paladin']),
            ('Thunderwave', 1, 'Evo', 'A', 'V/S', False, False, 'I', 'S',
             'Those within 15\' take 2d8 thunder damage and are pushed 10\' away.', ['Bard', 'Druid', 'Sorcerer', 'Wizard']),
            ('Wrathful Smite', 1, 'Evo', 'BA', 'V', True, False, '1m', 'S',
             'Next melee weapon attack deals 1d6 psychic damage.', ['Paladin']),

            # 2ND LEVEL SPELLS
            ('Acid Arrow', 2, 'Evo', 'A', 'V/S/M', False, False, 'I', '90\'',
             'Ranged spell attack deals 4d4 acid damage. At the end of the target\'s next turn, it takes 2d4 acid damage.', ['Wizard']),
            ('Aid', 2, 'Ench', 'A', 'V/S/M', False, False, '8h', '30\'',
             'For the duration, the target\'s hit point maximum and current hit points increase by 5.', ['Bard', 'Cleric', 'Paladin']),
            ('Alter Self', 2, 'Trans', 'A', 'V/S', True, False, '1h', 'S',
             'You assume a different form. When you cast the spell, choose one of the following options.', ['Sorcerer', 'Wizard']),
            ('Arcane Lock', 2, 'Abj', 'A', 'V/S/M', False, False, 'Sp', 'T',
             'You touch a closed door, window, gate, chest, or other closeable object. The object becomes locked if it isn\'t already.', ['Wizard']),
            ('Arcanist\'s Magic Aura', 2, 'Ill', 'A', 'V/S/M', False, False, '24h', 'T',
             'You place an illusion on a creature or an object you touch so that divination magic reveals false information.', ['Wizard', 'Bard']),
            ('Augury', 2, 'Div', 'A', 'V/S/M', False, True, 'I', 'S',
             'For this casting, you perceive the future as it branches along the path of the querent\'s immediate decision.', ['Cleric', 'Druid']),
            ('Barkskin', 2, 'Trans', 'A', 'V/S/M', True, False, '1h', 'T',
             'You touch a willing creature. Until the spell ends, the target\'s skin has a rough, bark-like appearance.', ['Druid', 'Ranger']),
            ('Beast Sense', 2, 'Div', 'A', 'V/S', True, True, '1h', 'T',
             'You touch a willing beast. For the duration of the spell, you can see through the beast\'s eyes and hear what it hears.', ['Druid', 'Ranger']),
            ('Blindness/Deafness', 2, 'Necro', 'A', 'V', True, False, '1m', '30\'',
             'For the spell\'s duration, the target is either blinded or deafened, as you choose.', ['Sorcerer', 'Wizard', 'Cleric']),
            ('Blur', 2, 'Ill', 'A', 'V', True, False, '1m', 'S',
             'Your body becomes blurred, shifting and wavering to all who can see you.', ['Sorcerer', 'Wizard']),
            ('Calm Emotions', 2, 'Ench', 'A', 'V/S', True, False, '1m', '60\'',
             'You attempt to suppress strong emotions in a group of people.', ['Bard', 'Cleric']),
            ('Continual Flame', 2, 'Evo', 'A', 'V/S/M', False, False, 'Sp', 'T',
             'A flame, equivalent in brightness to a torch, springs forth from an object that you touch.', ['Cleric', 'Wizard']),
            ('Darkness', 2, 'Evo', 'A', 'V/M', True, False, '10m', '60\'',
             'Magical darkness spreads from a point of your choice within range.', ['Sorcerer', 'Warlock', 'Wizard']),
            ('Darkvision', 2, 'Trans', 'A', 'V/S/M', False, False, '8h', 'T',
             'You touch a willing creature to grant it the ability to see in dim light within 60 feet as if it were bright light.', ['Druid', 'Ranger', 'Wizard']),
            ('Detect Thoughts', 2, 'Div', 'A', 'V/S/M', True, False, '1m', 'S',
             'For the spell\'s duration, you can sense the presence of thinking creatures within 30 feet of you.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Enhance Ability', 2, 'Trans', 'A', 'V/S/M', True, False, '1h', 'T',
             'You touch a creature and bestow upon it a magical enhancement. Choose one of the following effects.', ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Wizard']),
            ('Enthrall', 2, 'Ench', 'A', 'V/S', True, False, '1m', '60\'',
             'You weave a distracting string of words, causing creatures of your choice that you can see within 60 feet.', ['Bard', 'Warlock']),
            ('Find Traps', 2, 'Div', 'A', 'V/S', False, False, 'I', 'S',
             'You sense the presence of traps within 30 feet of you.', ['Cleric', 'Druid', 'Ranger', 'Wizard']),
            ('Flaming Sphere', 2, 'Conj', 'A', 'V/S/M', True, False, '1m', '60\'',
             'A 5-foot-diameter sphere of fire appears in an unoccupied space of your choice within range.', ['Druid', 'Sorcerer', 'Wizard']),
            ('Gentle Repose', 2, 'Necro', 'A', 'V/S/M', False, True, '10d', 'T',
             'You touch a corpse or other remains. For the duration, the body can\'t decay naturally.', ['Cleric', 'Wizard']),
            ('Gust of Wind', 2, 'Evo', 'A', 'V/S/M', True, False, '1m', 'S',
             'A line of strong wind 60 feet long and 10 feet wide blasts from you in a direction you choose for the spell\'s duration.', ['Druid', 'Sorcerer', 'Wizard']),
            ('Heat Metal', 2, 'Trans', 'A', 'V/S/M', True, False, '1m', '60\'',
             'Choose a manufactured metal object, such as a metal weapon or a suit of heavy or medium metal armor.', ['Bard', 'Druid']),
            ('Hold Person', 2, 'Ench', 'A', 'V/S/M', True, False, '1m', '60\'',
             'Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw.', ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Identify', 2, 'Div', 'L', 'V/S/M*', False, True, 'I', 'T',
             'Choose one object that you must touch throughout the casting of this spell.', ['Bard', 'Wizard']),
            ('Invisibility', 2, 'Ill', 'A', 'V/S/M', True, False, '1h', 'T',
             'A creature you touch becomes invisible until the spell ends.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Knock', 2, 'Trans', 'A', 'V', False, False, 'I', '60\'',
             'Choose an object that you can see within range. The object can be a door, box, chest, lock, or other object.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Lesser Restoration', 2, 'Abo', 'A', 'V/S', False, False, 'I', 'T',
             'You touch a creature and can end either one disease or one condition afflicting it.', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger']),
            ('Levitate', 2, 'Trans', 'A', 'V/S/M', True, False, '10m', '60\'',
             'One creature of your choice that you can see within range rises vertically, up to 20 feet.', ['Sorcerer', 'Wizard']),
            ('Locate Animals or Plants', 2, 'Div', 'A', 'V/S/M', False, True, 'I', 'S',
             'Describe or name a specific kind of beast or plant. Concentrating on the spell, you sense the direction and distance.', ['Bard', 'Druid', 'Ranger']),
            ('Locate Object', 2, 'Div', 'A', 'V/S/M', True, False, '10m', 'S',
             'Describe or name an object that is familiar to you. You sense the direction to the object\'s location.', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Wizard']),
            ('Magic Mouth', 2, 'Ill', 'A', 'V/S/M', False, True, 'I', '30\'',
             'You implant a message within an object in range, a message that is uttered when a trigger occurs.', ['Bard', 'Wizard']),
            ('Magic Weapon', 2, 'Trans', 'BA', 'V/S', True, False, '1h', 'T',
             'You touch a nonmagical weapon. Until the spell ends, that weapon becomes a magic weapon with a +1 bonus.', ['Paladin', 'Wizard']),
            ('Melf\'s Acid Arrow', 2, 'Evo', 'A', 'V/S/M', False, False, 'I', '90\'',
             'A shimmering green arrow streaks toward a target within range.', ['Wizard', 'Sorcerer']),
            ('Mirror Image', 2, 'Ill', 'A', 'V/S', False, False, '1m', 'S',
             'Three illusory duplicates of yourself appear in your space.', ['Sorcerer', 'Warlock', 'Wizard']),
            ('Misty Step', 2, 'Conj', 'BA', 'V', False, False, 'I', 'S',
             'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Moonbeam', 2, 'Evo', 'A', 'V/S/M', True, False, '1m', '120\'',
             'A silvery beam of pale radiance springs from your hand into a cylinder 5 feet in radius.', ['Druid']),
            ('Pass Without Trace', 2, 'Trans', 'A', 'V/S/M', True, False, '1h', 'S',
             'A veil of shadows and silence radiates from you. For the duration, each creature of your choice.', ['Bard', 'Druid', 'Ranger']),
            ('Phantasmal Force', 2, 'Ill', 'A', 'V/S/M', True, False, '1m', '60\'',
             'You craft an illusory creature in the mind of a creature that you can see within range.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Prayer of Healing', 2, 'Evo', 'L', 'V', False, False, 'I', '30\'',
             'Up to six creatures of your choice that you can see within range each regain hit points.', ['Cleric', 'Druid']),
            ('Pyrotechnics', 2, 'Trans', 'A', 'V/S', False, False, 'I', '60\'',
             'Choose an area of nonmagical flame that you can see and that fits within a 5-foot cube within range.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Ray of Enfeeblement', 2, 'Necro', 'A', 'V/S', True, False, '1m', '60\'',
             'A black beam of enervating energy springs from your finger toward a creature within range.', ['Warlock', 'Wizard']),
            ('Rope Trick', 2, 'Trans', 'A', 'V/S/M', False, False, '1h', 'T',
             'You touch a length of rope 10 feet long. One end of the rope then rises into the air.', ['Wizard', 'Artificer']),
            ('Scorching Ray', 2, 'Evo', 'A', 'V/S', False, False, 'I', '120\'',
             'Each creature in a 5-foot-wide, 30-foot-long line originating from you takes 3d6 fire damage.', ['Sorcerer', 'Wizard']),
            ('See Invisibility', 2, 'Div', 'A', 'V/S/M', False, False, '1h', 'S',
             'For the spell\'s duration, you see invisible creatures and objects as if they were visible.', ['Sorcerer', 'Wizard', 'Bard']),
            ('Shatter', 2, 'Evo', 'A', 'V/S/M', False, False, 'I', '60\'',
             'A sudden loud ringing noise, painfully intense, erupts from a point of your choice within range.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Silence', 2, 'Ill', 'A', 'V/S', True, False, '1m', '120\'',
             'For the duration, no sound can be created within or travel through a 20-foot-radius sphere centered on a point.', ['Bard', 'Cleric']),
            ('Spider Climb', 2, 'Trans', 'A', 'V/S/M', True, False, '1h', 'T',
             'Until the spell ends, one willing creature you touch gains the ability to move up, down, and across vertical surfaces.', ['Sorcerer', 'Warlock', 'Wizard']),
            ('Spiritual Weapon', 2, 'Evo', 'BA', 'V/S', True, False, '1m', '60\'',
             'You create a floating, spectral weapon within range that lasts for the duration of the spell.', ['Cleric']),
            ('Suggestion', 2, 'Ench', 'A', 'V/M', True, False, '8h', '30\'',
             'You suggest a course of activity, phrased in such a way as to make the activity sound reasonable.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Web', 2, 'Conj', 'A', 'V/S/M', True, False, '1h', '60\'',
             'You conjure a mass of thick, sticky webbing at a point of your choice within range.', ['Sorcerer', 'Wizard']),
            ('Wither and Bloom', 2, 'Trans', 'A', 'V/S', True, False, '1m', '60\'',
             'Choose a creature you can see within range. One creature of your choice within 30 feet of the target.', ['Druid']),

            # 3RD LEVEL SPELLS
            ('Animate Dead', 3, 'Necro', 'L', 'V/S/M', False, False, 'I', '10\'',
             'You can cast this spell only at night. Choose up to three corpses of Medium or Small humanoids within range.', ['Cleric', 'Wizard']),
            ('Aura of Vitality', 3, 'Evo', 'A', 'V', True, False, '1m', 'S',
             'Emanates a 30-foot aura of pulsing energy. If a creature is prone or has 0 hit points when it enters the aura for the first time.', ['Paladin']),
            ('Beacon of Hope', 3, 'Abo', 'A', 'V/S', True, False, '1m', '30\'',
             'This spell grants the willing creatures you designate within 30 feet advantage on all their attack rolls and ability checks.', ['Cleric']),
            ('Bestow Curse', 3, 'Ench', 'A', 'V/S', True, False, '1m', 'T',
             'You touch a creature, and that creature must succeed on a Wisdom saving throw or become cursed for the duration.', ['Bard', 'Cleric', 'Wizard']),
            ('Blinding Smite', 3, 'Evo', 'BA', 'V', True, False, '1m', 'S',
             'The next time you hit a creature with a weapon attack before the spell ends, your attack glows with bright, searing light.', ['Paladin']),
            ('Blink', 3, 'Trans', 'A', 'V/S', False, False, '1m', 'S',
             'Roll a d20 after you cast this spell. While the spell lasts, roll a d20 at the end of each of your turns.', ['Sorcerer', 'Wizard']),
            ('Catnap', 3, 'Ench', 'A', 'S', False, False, '1m', '30\'',
             'You make a calming gesture, and up to three willing creatures of your choice that you can see within range fall unconscious.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Clairvoyance', 3, 'Div', 'L', 'V/S/M', True, False, '10m', '1 mile',
             'You can see through solid walls, doors, and other barriers as if they were transparent.', ['Bard', 'Cleric', 'Sorcerer', 'Wizard']),
            ('Conjure Animals', 3, 'Conj', 'A', 'V/S', True, False, '1h', '60\'',
             'You summon fey spirits that take the form of beasts and appear in unoccupied spaces that you can see within range.', ['Druid', 'Ranger']),
            ('Counterspell', 3, 'Abj', 'RA', 'V/S', False, False, 'I', '60\'',
             'You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower.', ['Sorcerer', 'Warlock', 'Wizard']),
            ('Create Food and Water', 3, 'Conj', 'A', 'V/S', False, False, 'I', '30\'',
             'You create 45 pounds of food and 30 gallons of water on the ground or in containers within range.', ['Cleric', 'Paladin']),
            ('Crusader\'s Mantle', 3, 'Evo', 'A', 'V', True, False, '1m', 'S',
             'Holy power radiates from you in an aura with a 30-foot radius. Until the spell ends, the aura moves with you.', ['Paladin']),
            ('Daylight', 3, 'Evo', 'A', 'V/S/M', False, False, '1h', '60\'',
             'A 60-foot-radius sphere of light spreads out from a point of your choice within range. The sphere is bright light.', ['Cleric', 'Druid', 'Paladin', 'Ranger', 'Sorcerer', 'Wizard']),
            ('Dispel Magic', 3, 'Abj', 'A', 'V/S', False, False, 'I', '120\'',
             'Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends.', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Elemental Weapon', 3, 'Trans', 'BA', 'V/S', True, False, '1h', 'T',
             'A nonmagical weapon you touch becomes a magic weapon. Choose one of the following damage types: acid, cold, fire, lightning, or thunder.', ['Paladin', 'Ranger']),
            ('Enemies Abound', 3, 'Ench', 'A', 'V/S', True, False, '1m', '120\'',
             'For the spell\'s duration, each creature that starts its turn within 120 feet of the target must succeed on a Wisdom saving throw.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Erupting Earth', 3, 'Trans', 'A', 'V/S/M', False, False, 'I', '120\'',
             'Choose a point you can see on the ground within range. A fountain of churned earth and stone erupts in a 20-foot cube.', ['Druid', 'Sorcerer', 'Wizard']),
            ('Feign Death', 3, 'Necro', 'A', 'V/S', False, True, '1h', 'T',
             'You touch a corpse or other remains. For the duration, the body can\'t decay naturally.', ['Bard', 'Cleric', 'Druid', 'Wizard']),
            ('Fireball', 3, 'Evo', 'A', 'V/S/M', False, False, 'I', '150\'',
             'A bright streak flashes from your pointing finger to a point of your choice within range and then blossoms with a low roar into an explosion of flame.', ['Sorcerer', 'Wizard']),
            ('Fly', 3, 'Trans', 'A', 'V/S/M', True, False, '10m', 'T',
             'You touch a willing creature. The target gains a flying speed of 60 feet for the duration.', ['Sorcerer', 'Wizard']),
            ('Glyph of Warding', 3, 'Abj', 'L', 'V/S/M', False, False, 'I', 'T',
             'When you cast this spell, you inscribe a glyph that harms other creatures, using either ink, blood, powdered diamond, emeralds, opal, or rubies.', ['Bard', 'Cleric', 'Druid', 'Ranger', 'Sorcerer', 'Wizard']),
            ('Haste', 3, 'Trans', 'A', 'V/S/M', True, False, '1m', '30\'',
             'Choose a willing creature that you can see within range. Until the spell ends, the creature\'s speed is doubled.', ['Sorcerer', 'Wizard']),
            ('Hunger of Hadar', 3, 'Conj', 'A', 'V/S/M', True, False, '1m', '150\'',
             'A 20-foot-radius sphere of blackest tentacles springs into existence centered on a point of your choice within range.', ['Warlock']),
            ('Hypnotic Pattern', 3, 'Ill', 'A', 'V/S/M', True, False, '1m', '120\'',
             'A swirling pattern of colors springs from your pointed finger in a 30-foot cone. Each creature in the area who sees the pattern.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Intellect Fortress', 3, 'Abj', 'A', 'V', True, False, '1m', '30\'',
             'For the spell\'s duration, you or one willing creature you can see within range has resistance to psychic damage.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Invisibility to Undead', 3, 'Abj', 'A', 'V/S/M', True, False, '1h', '60\'',
             'For the spell\'s duration, each creature you designate when you cast the spell is invisible to undead.', ['Cleric', 'Druid', 'Paladin', 'Ranger', 'Wizard']),
            ('Leomund\'s Tiny Hut', 3, 'Evo', 'L', 'V/S/M', False, True, '8h', 'S',
             'A 15-foot-radius immobile dome of invisible force springs into existence around and above you.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Lightning Bolt', 3, 'Evo', 'A', 'V/S/M', False, False, 'I', 'S',
             'A stroke of lightning forming a line of 100 feet long and 5 feet wide blasts out from you in a direction you choose.', ['Sorcerer', 'Wizard']),
            ('Magic Circle', 3, 'Abj', 'L', 'V/S/M', False, False, '1h', '10\'',
             'You draw a 10-foot-radius circle on the ground with the blood of an evil creature.', ['Bard', 'Cleric', 'Paladin', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Meld Into Stone', 3, 'Trans', 'A', 'V/S', False, True, '8h', 'T',
             'You step into a stone object or surface large enough to fully contain your body, melting into the stone as if it were clay.', ['Cleric', 'Druid', 'Ranger', 'Wizard']),
            ('Nondetection', 3, 'Abj', 'A', 'V/S/M', False, False, '8h', 'T',
             'For the duration, you hide a willing creature you touch from divination magic.', ['Bard', 'Ranger', 'Wizard']),
            ('Phantom Steed', 3, 'Ill', 'L', 'V/S', False, False, '1h', '30\'',
             'A Large quasi-real, horselike creature appears on the ground in an unoccupied space of your choice within range.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Revivify', 3, 'Evo', 'A', 'V/S/M', False, False, 'I', 'T',
             'You touch a creature that has been dead for no longer than 1 minute. That creature returns to life with 1 hit point.', ['Cleric', 'Paladin']),
            ('Sending', 3, 'Evo', 'A', 'V/S/M', False, False, '1r', 'Unlimited',
             'You send a short message of twenty-five words or fewer to a creature with which you are familiar.', ['Bard', 'Cleric', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Sleet Storm', 3, 'Conj', 'A', 'V/S/M', True, False, '1m', '150\'',
             'Until the spell ends, freezing rain and sleet fall in a 20-foot-tall cylinder with a 40-foot radius centered on a point you choose.', ['Druid', 'Sorcerer', 'Wizard']),
            ('Slow', 3, 'Trans', 'A', 'V/S/M', True, False, '1m', '120\'',
             'You can alter the fabric of time around a creature that you can see within range. An unwilling creature must make a Wisdom saving throw.', ['Sorcerer', 'Wizard']),
            ('Speak with Dead', 3, 'Necro', 'L', 'V/S/M', False, False, '10m', '5\'',
             'You grant the semblance of life and intelligence to a corpse within range, allowing it to answer the questions you pose.', ['Bard', 'Cleric', 'Druid', 'Ranger', 'Wizard']),
            ('Stinking Cloud', 3, 'Conj', 'A', 'V/S/M', True, False, '1m', '90\'',
             'A 20-foot-radius sphere of yellow, nauseating gas springs from a point of your choice within range.', ['Sorcerer', 'Wizard']),
            ('Summon Lesser Demon', 3, 'Conj', 'A', 'V/S/M', True, False, '1h', '30\'',
             'You utter foul words, summoning one demon from the chaos of the Abyss. You choose the demon\'s type.', ['Warlock', 'Wizard']),
            ('Summon Undead', 3, 'Necro', 'A', 'V/S/M', True, False, '1h', '10\'',
             'You call forth the spirit of a dead humanoid you knew in life, projecting it in an unoccupied space you can see within range.', ['Cleric', 'Warlock', 'Wizard']),
            ('Summon Construct', 3, 'Conj', 'A', 'V/S/M', True, False, '1h', '90\'',
             'You summon a construct in an unoccupied space that you can see within range. Choose the construct\'s appearance.', ['Artificer', 'Wizard']),
            ('Summon Fey', 3, 'Conj', 'A', 'V/S/M', True, False, '1h', '90\'',
             'You summon a fey creature in an unoccupied space that you can see within range. Choose the fey creature\'s appearance.', ['Bard', 'Druid', 'Ranger', 'Wizard']),
            ('Telekinesis', 3, 'Trans', 'A', 'V/S', True, False, '10m', '60\'',
             'You gain the ability to move or manipulate creatures or objects by thought. When you cast the spell.', ['Sorcerer', 'Wizard']),
            ('Teleport', 3, 'Conj', 'A', 'V', False, False, 'I', '10\'',
             'This spell instantly transports you and up to eight willing creatures of your choice that you can see within range.', ['Sorcerer', 'Wizard', 'Warlock']),
            ('Tidal Wave', 3, 'Conj', 'A', 'V/S/M', False, False, 'I', '120\'',
             'You summon a wave of seawater that crashes down on an area of your choice within range. The area can be up to 300 feet long, 300 feet wide.', ['Druid', 'Sorcerer', 'Wizard']),
            ('Tiny Hut', 3, 'Evo', 'L', 'V/S/M', False, True, '8h', 'S',
             'A 15-foot-radius immobile dome of invisible force springs into existence around and above you.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Vampiric Touch', 3, 'Necro', 'A', 'V/S', True, False, '1m', 'S',
             'The touch of your shadow-wreathed hand can siphon life force from others to heal your wounds.', ['Wizard']),
            ('Vortex Warp', 3, 'Trans', 'A', 'V/S', False, False, 'I', '90\'',
             'You open a swirling vortex connecting two points you can see within range. The vortex persists in the air until the spell ends.', ['Sorcerer', 'Wizard']),
            ('Wall of Sand', 3, 'Evo', 'A', 'V/S/M', True, False, '10m', '90\'',
             'You create a wall of swirling sand on solid ground within range. You can make the wall up to 30 feet long.', ['Druid', 'Sorcerer', 'Wizard']),
            ('Wall of Water', 3, 'Evo', 'A', 'V/S', True, False, '10m', '60\'',
             'You conjure up a wall of fresh water that can be up to 30 feet long, 10 feet high, and 1 foot thick.', ['Druid', 'Sorcerer', 'Wizard']),
            ('Watery Sphere', 3, 'Conj', 'A', 'V/S/M', True, False, '1m', '90\'',
             'You conjure up a sphere of water centered on a point you can see within range. The sphere can have a radius of up to 10 feet.', ['Druid', 'Sorcerer', 'Wizard']),
        ]

        created_count = 0
        for spell_data in spells_data:
            name, level, category, casting_time, components, concentration, ritual, duration, range_str, description, spell_classes = spell_data
            
            spell, created = Spell.objects.get_or_create(
                name=name,
                defaults={
                    'level': level,
                    'category': category,
                    'casting_time': casting_time,
                    'components': components,
                    'requires_concentration': concentration,
                    'ritual': ritual,
                    'duration': duration,
                    'spell_range': range_str,
                    'description': description,
                }
            )
            
            if created:
                created_count += 1
                for class_name in spell_classes:
                    if class_name in class_objs:
                        spell.available_to_classes.add(class_objs[class_name])
                self.stdout.write(f"Created spell: {name}")

        self.stdout.write(self.style.SUCCESS(f"Successfully created {created_count} spells"))
