from django.core.management.base import BaseCommand
from base.models import Spell, SpellcastingClass

class Command(BaseCommand):
    help = 'Populate database with D&D 5e spells'

    def handle(self, *args, **options):
        # Create SpellcastingClass instances
        classes = [
            'Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 
            'Sorcerer', 'Warlock', 'Wizard'
        ]
        
        class_objs = {}
        for class_name in classes:
            obj, created = SpellcastingClass.objects.get_or_create(name=class_name)
            class_objs[class_name] = obj
            if created:
                self.stdout.write(f"Created class: {class_name}")

        # Parse and add spells
        spells_data = [
            # CANTRIPS (Level 0)
            ('Acid Splash', 0, 'Conj', 'A', 'V/S', False, False, 'I', '60\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Blade Ward', 0, 'Abj', 'A', 'V/S', False, False, '1r', 'S', 
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Chill Touch', 0, 'Necro', 'A', 'V/S', False, False, '1r', '120\'',
             'Target takes 1d8 necrotic damage and can\' ', ['Sorcerer', 'Warlock', 'Wizard']),
            ('Dancing Lights', 0, 'Evo', 'A', 'V/S/M', True, False, '1m', '120\'',
             'Creates four torch-sized lights, which illuminate 10\' and can be moved 60\' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Druidcraft', 0, 'Trans', 'A', 'V/S', False, False, 'I', '30\'',
             ' ', ['Druid']),
            ('Eldritch Blast', 0, 'Evo', 'A', 'V/S', False, False, 'I', '120\'',
             ' ', ['Warlock']),
            ('Fire Bolt', 0, 'Evo', 'A', 'V/S', False, False, 'I', '120\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Friends', 0, 'Ench', 'A', 'S/M', True, False, '1m', 'S',
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Guidance', 0, 'Div', 'A', 'V/S', True, False, '1m', 'T',
             ' ', ['Cleric', 'Druid']),
            ('Light', 0, 'Evo', 'A', 'V/M', False, False, '1h', 'T',
             'Object sheds 20\' of bright light and an additional 20\' ', ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Wizard']),
            ('Mage Hand', 0, 'Conj', 'A', 'V/S', False, False, '1m', '30\'',
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Mending', 0, 'Trans', 'L', 'V/S/M', False, False, 'I', 'T',
             ' ', ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Wizard']),
            ('Message', 0, 'Trans', 'A', 'V/S/M', False, False, '1r', '120\'',
             ' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Minor Illusion', 0, 'Ill', 'A', 'S/M', False, False, '1m', '30\'',
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Poison Spray', 0, 'Conj', 'A', 'V/S', False, False, 'I', '10\'',
             ' ', ['Druid', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Prestidigitation', 0, 'Trans', 'A', 'V/S', False, False, 'Sp', '10\'',
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Produce Flames', 0, 'Conj', 'A', 'V/S', False, False, '10m', 'S',
             'Ranged spell attack within 30\' ', ['Druid']),
            ('Ray of Frost', 0, 'Evo', 'A', 'V/S', False, False, 'I', '60\'',
             'Target takes 1d8 cold damage and loses 10\' ', ['Sorcerer', 'Wizard']),
            ('Resistance', 0, 'Abj', 'A', 'V/S/M', True, False, '1m', 'T',
             ' ', ['Cleric', 'Druid']),
            ('Sacred Flame', 0, 'Evo', 'A', 'V/S', False, False, 'I', '60\'',
             ' ', ['Cleric']),
            ('Shillelagh', 0, 'Trans', 'BA', 'V/S/M', False, False, '1m', 'T',
             ' ', ['Druid']),
            ('Shocking Grasp', 0, 'Evo', 'A', 'V/S', False, False, 'I', 'T',
             'Target takes 1d8 lightning damage, and can\' ', ['Sorcerer', 'Wizard']),
            ('Spare the Dying', 0, 'Necro', 'A', 'V/S', False, False, 'I', 'T',
             ' ', ['Cleric']),
            ('Thaumaturgy', 0, 'Trans', 'A', 'V', False, False, '1m', '30\'',
             ' ', ['Cleric']),
            ('Thorn Whip', 0, 'Trans', 'A', 'V/S/M', False, False, 'I', '30\'',
             ' ', ['Druid']),
            ('True Strike', 0, 'Div', 'A', 'S', True, False, '1r', '30\'',
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Vicious Mockery', 0, 'Ench', 'A', 'V', False, False, 'I', '60\'',
             ' ', ['Bard']),

            # 1ST LEVEL SPELLS
            ('Alarm', 1, 'Abj', 'L', 'V/S/M', False, True, '8h', '30\'',
             'Sets an alarm which pings you if you\' ', ['Ranger', 'Wizard']),
            ('Animal Friendship', 1, 'Ench', 'A', 'V/S/M', False, False, '24h', '30\'',
             ' ', ['Bard', 'Druid', 'Ranger']),
            ('Armor of Agathys', 1, 'Abj', 'A', 'V/S/M', False, False, '1h', 'S',
             ' ', ['Warlock']),
            ('Bane', 1, 'Ench', 'A', 'V/S/M', True, False, '1m', '30\'',
             ' ', ['Bard', 'Cleric']),
            ('Bless', 1, 'Ench', 'A', 'V/S/M', True, False, '1m', '30\'',
             ' ', ['Cleric', 'Paladin']),
            ('Burning Hands', 1, 'Evo', 'A', 'V/S', False, False, 'I', 'S',
             '3d6 fire damage to creatures in 15\' ', ['Sorcerer', 'Wizard']),
            ('Charm Person', 1, 'Ench', 'A', 'V/S', False, False, '1h', '30\'',
             ' ', ['Bard', 'Druid', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Color Spray', 1, 'Ill', 'A', 'V/S', False, False, 'I', 'S',
             'Spray of colors blinds, stuns, or knocks unconscious creatures in a 15\' ', ['Sorcerer', 'Wizard']),
            ('Command', 1, 'Ench', 'A', 'V', False, False, '1r', '60\'',
             ' ', ['Cleric', 'Paladin']),
            ('Compelled Duel', 1, 'Ench', 'BA', 'V', True, False, '1m', '30\'',
             ' ', ['Paladin']),
            ('Comprehend Languages', 1, 'Div', 'A', 'V/S/M', False, True, '1h', 'S',
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Cure Wounds', 1, 'Evo', 'A', 'V/S', False, False, 'I', 'T',
             ' ', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger']),
            ('Detect Evil or Good', 1, 'Div', 'A', 'V/S', True, False, '10m', 'S',
             'Recognizes aberration, celestial, fey, fiend, or undead within 30\' ', ['Cleric', 'Paladin']),
            ('Detect Magic', 1, 'Div', 'A', 'V/S', True, True, '10m', 'S',
             'Senses magical objects or creatures within 30\' ', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Detect Poison and Disease', 1, 'Div', 'A', 'V/S/M', True, True, '10m', 'S',
             'Senses poison, poisonous creatures, and disease within 30\' ', ['Cleric', 'Druid', 'Paladin', 'Ranger']),
            ('Disguise Self', 1, 'Ill', 'A', 'V/S', False, False, '1h', 'S',
             ' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Dissonant Whispers', 1, 'Ench', 'A', 'V', False, False, 'I', '60\'',
             ' ', ['Bard']),
            ('Divine Favor', 1, 'Evo', 'BA', 'V/S', True, False, '1m', 'S',
             ' ', ['Paladin']),
            ('Ensnaring Strike', 1, 'Conj', 'BA', 'V', True, False, '1m', 'S',
             ' ', ['Ranger']),
            ('Faerie Fire', 1, 'Evo', 'A', 'V', True, False, '1m', '60\'',
             'Objects and people in a 20\' ', ['Bard', 'Druid']),
            ('Feather Fall', 1, 'Trans', 'RA', 'V/M', False, False, '1m', '60\'',
             'Up to five falling creatures have their descent velocity capped at 60\' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Find Familiar', 1, 'Conj', 'L', 'V/S/M', False, True, 'I', '10\'',
             ' ', ['Wizard', 'Warlock']),
            ('Fog Cloud', 1, 'Conj', 'A', 'V/S', True, False, '1h', '120\'',
             '20\' ', ['Bard', 'Druid', 'Ranger', 'Sorcerer', 'Wizard']),
            ('Goodberry', 1, 'Trans', 'A', 'V/S/M', False, False, 'I', 'T',
             ' ', ['Druid', 'Ranger']),
            ('Guiding Bolt', 1, 'Evo', 'A', 'V/S', False, False, '1r', '120\'',
             ' ', ['Cleric']),
            ('Hail of Thorns', 1, 'Conj', 'BA', 'V', True, False, '1m', 'S',
             'Around next creature struck with ranged weapon attack, deal 1d10 pierce to target and all within 5\' ', ['Ranger']),
            ('Healing Word', 1, 'Evo', 'BA', 'V', False, False, 'I', '60\'',
             ' ', ['Bard', 'Cleric', 'Druid', 'Paladin']),
            ('Heroism', 1, 'Ench', 'A', 'V/S', True, False, '1m', 'T',
             ' ', ['Bard', 'Paladin']),
            ('Hunter\'s Mark', 1, 'Div', 'BA', 'V', True, False, '1h', '90\'',
             ' ', ['Ranger']),
            ('Identify', 1, 'Div', 'L', 'V/S/M*', False, True, 'I', 'T',
             ' ', ['Bard', 'Wizard']),
            ('Jump', 1, 'Trans', 'A', 'V/S/M', False, False, '1m', 'T',
             'Triples target\' ', ['Bard', 'Druid', 'Ranger', 'Sorcerer', 'Wizard']),
            ('Longstrider', 1, 'Trans', 'A', 'V/S/M', False, False, '1h', 'T',
             'Target\'s speed increases by +10\' ', ['Bard', 'Druid', 'Ranger', 'Wizard']),
            ('Magic Missile', 1, 'Evo', 'A', 'V/S', False, False, 'I', '120\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Protection from Evil and Good', 1, 'Abj', 'A', 'V/S/M', True, False, '10m', 'T',
             ' ', ['Cleric', 'Paladin', 'Warlock', 'Wizard']),
            ('Searing Smite', 1, 'Evo', 'BA', 'V', True, False, '1m', 'S',
             ' ', ['Paladin']),
            ('Shield', 1, 'Abj', 'RA', 'V/S', False, False, '1r', 'S',
             ' ', ['Sorcerer', 'Wizard']),
            ('Shield of Faith', 1, 'Abj', 'BA', 'V/S/M', True, False, '10m', '60\'',
             ' ', ['Cleric', 'Paladin']),
            ('Silent Image', 1, 'Ill', 'A', 'V/S/M', True, False, '10m', '60\'',
             ' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Sleep', 1, 'Ench', 'A', 'V/S/M', False, False, '1m', '90\'',
             ' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Speak with Animals', 1, 'Div', 'A', 'V/S', False, True, '10m', 'S',
             ' ', ['Bard', 'Druid', 'Ranger']),
            ('Tasha\'s Hideous Laughter', 1, 'Ench', 'A', 'V/S/M', True, False, '1m', '60\'',
             ' ', ['Bard', 'Wizard']),
            ('Thunderous Smite', 1, 'Evo', 'BA', 'V', True, False, '1m', 'S',
             'Next attack deals 2d6 thunder damage to the target and pushes it 10\' ', ['Paladin']),
            ('Thunderwave', 1, 'Evo', 'A', 'V/S', False, False, 'I', 'S',
             'Those within 15\' take 2d8 thunder damage and are pushed 10\' ', ['Bard', 'Druid', 'Sorcerer', 'Wizard']),
            ('Wrathful Smite', 1, 'Evo', 'BA', 'V', True, False, '1m', 'S',
             ' ', ['Paladin']),

            # 2ND LEVEL SPELLS
            ('Acid Arrow', 2, 'Evo', 'A', 'V/S/M', False, False, 'I', '90\'',
             'Ranged spell attack deals 4d4 acid damage. At the end of the target\' ', ['Wizard']),
            ('Aid', 2, 'Ench', 'A', 'V/S/M', False, False, '8h', '30\'',
             'For the duration, the target\' ', ['Bard', 'Cleric', 'Paladin']),
            ('Alter Self', 2, 'Trans', 'A', 'V/S', True, False, '1h', 'S',
             ' ', ['Sorcerer', 'Wizard']),
            ('Arcane Lock', 2, 'Abj', 'A', 'V/S/M', False, False, 'Sp', 'T',
             'You touch a closed door, window, gate, chest, or other closeable object. The object becomes locked if it isn\' ', ['Wizard']),
            ('Arcanist\'s Magic Aura', 2, 'Ill', 'A', 'V/S/M', False, False, '24h', 'T',
             ' ', ['Wizard', 'Bard']),
            ('Augury', 2, 'Div', 'A', 'V/S/M', False, True, 'I', 'S',
             'For this casting, you perceive the future as it branches along the path of the querent\' ', ['Cleric', 'Druid']),
            ('Barkskin', 2, 'Trans', 'A', 'V/S/M', True, False, '1h', 'T',
             'You touch a willing creature. Until the spell ends, the target\' ', ['Druid', 'Ranger']),
            ('Beast Sense', 2, 'Div', 'A', 'V/S', True, True, '1h', 'T',
             'You touch a willing beast. For the duration of the spell, you can see through the beast\' ', ['Druid', 'Ranger']),
            ('Blindness/Deafness', 2, 'Necro', 'A', 'V', True, False, '1m', '30\'',
             'For the spell\' ', ['Sorcerer', 'Wizard', 'Cleric']),
            ('Blur', 2, 'Ill', 'A', 'V', True, False, '1m', 'S',
             ' ', ['Sorcerer', 'Wizard']),
            ('Calm Emotions', 2, 'Ench', 'A', 'V/S', True, False, '1m', '60\'',
             ' ', ['Bard', 'Cleric']),
            ('Continual Flame', 2, 'Evo', 'A', 'V/S/M', False, False, 'Sp', 'T',
             ' ', ['Cleric', 'Wizard']),
            ('Darkness', 2, 'Evo', 'A', 'V/M', True, False, '10m', '60\'',
             ' ', ['Sorcerer', 'Warlock', 'Wizard']),
            ('Darkvision', 2, 'Trans', 'A', 'V/S/M', False, False, '8h', 'T',
             ' ', ['Druid', 'Ranger', 'Wizard']),
            ('Detect Thoughts', 2, 'Div', 'A', 'V/S/M', True, False, '1m', 'S',
             'For the spell\' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Enhance Ability', 2, 'Trans', 'A', 'V/S/M', True, False, '1h', 'T',
             ' ', ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Wizard']),
            ('Enthrall', 2, 'Ench', 'A', 'V/S', True, False, '1m', '60\'',
             ' ', ['Bard', 'Warlock']),
            ('Find Traps', 2, 'Div', 'A', 'V/S', False, False, 'I', 'S',
             ' ', ['Cleric', 'Druid', 'Ranger', 'Wizard']),
            ('Flaming Sphere', 2, 'Conj', 'A', 'V/S/M', True, False, '1m', '60\'',
             ' ', ['Druid', 'Sorcerer', 'Wizard']),
            ('Gentle Repose', 2, 'Necro', 'A', 'V/S/M', False, True, '10d', 'T',
             'You touch a corpse or other remains. For the duration, the body can\' ', ['Cleric', 'Wizard']),
            ('Gust of Wind', 2, 'Evo', 'A', 'V/S/M', True, False, '1m', 'S',
             'A line of strong wind 60 feet long and 10 feet wide blasts from you in a direction you choose for the spell\' ', ['Druid', 'Sorcerer', 'Wizard']),
            ('Heat Metal', 2, 'Trans', 'A', 'V/S/M', True, False, '1m', '60\'',
             ' ', ['Bard', 'Druid']),
            ('Hold Person', 2, 'Ench', 'A', 'V/S/M', True, False, '1m', '60\'',
             ' ', ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Identify', 2, 'Div', 'L', 'V/S/M*', False, True, 'I', 'T',
             ' ', ['Bard', 'Wizard']),
            ('Invisibility', 2, 'Ill', 'A', 'V/S/M', True, False, '1h', 'T',
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Knock', 2, 'Trans', 'A', 'V', False, False, 'I', '60\'',
             ' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Lesser Restoration', 2, 'Abo', 'A', 'V/S', False, False, 'I', 'T',
             ' ', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger']),
            ('Levitate', 2, 'Trans', 'A', 'V/S/M', True, False, '10m', '60\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Locate Animals or Plants', 2, 'Div', 'A', 'V/S/M', False, True, 'I', 'S',
             ' ', ['Bard', 'Druid', 'Ranger']),
            ('Locate Object', 2, 'Div', 'A', 'V/S/M', True, False, '10m', 'S',
             'Describe or name an object that is familiar to you. You sense the direction to the object\' ', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Wizard']),
            ('Magic Mouth', 2, 'Ill', 'A', 'V/S/M', False, True, 'I', '30\'',
             ' ', ['Bard', 'Wizard']),
            ('Magic Weapon', 2, 'Trans', 'BA', 'V/S', True, False, '1h', 'T',
             ' ', ['Paladin', 'Wizard']),
            ('Melf\'s Acid Arrow', 2, 'Evo', 'A', 'V/S/M', False, False, 'I', '90\'',
             ' ', ['Wizard', 'Sorcerer']),
            ('Mirror Image', 2, 'Ill', 'A', 'V/S', False, False, '1m', 'S',
             ' ', ['Sorcerer', 'Warlock', 'Wizard']),
            ('Misty Step', 2, 'Conj', 'BA', 'V', False, False, 'I', 'S',
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Moonbeam', 2, 'Evo', 'A', 'V/S/M', True, False, '1m', '120\'',
             ' ', ['Druid']),
            ('Pass Without Trace', 2, 'Trans', 'A', 'V/S/M', True, False, '1h', 'S',
             ' ', ['Bard', 'Druid', 'Ranger']),
            ('Phantasmal Force', 2, 'Ill', 'A', 'V/S/M', True, False, '1m', '60\'',
             ' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Prayer of Healing', 2, 'Evo', 'L', 'V', False, False, 'I', '30\'',
             ' ', ['Cleric', 'Druid']),
            ('Pyrotechnics', 2, 'Trans', 'A', 'V/S', False, False, 'I', '60\'',
             ' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Ray of Enfeeblement', 2, 'Necro', 'A', 'V/S', True, False, '1m', '60\'',
             ' ', ['Warlock', 'Wizard']),
            ('Rope Trick', 2, 'Trans', 'A', 'V/S/M', False, False, '1h', 'T',
             ' ', ['Wizard', 'Artificer']),
            ('Scorching Ray', 2, 'Evo', 'A', 'V/S', False, False, 'I', '120\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('See Invisibility', 2, 'Div', 'A', 'V/S/M', False, False, '1h', 'S',
             'For the spell\' ', ['Sorcerer', 'Wizard', 'Bard']),
            ('Shatter', 2, 'Evo', 'A', 'V/S/M', False, False, 'I', '60\'',
             ' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Silence', 2, 'Ill', 'A', 'V/S', True, False, '1m', '120\'',
             ' ', ['Bard', 'Cleric']),
            ('Spider Climb', 2, 'Trans', 'A', 'V/S/M', True, False, '1h', 'T',
             ' ', ['Sorcerer', 'Warlock', 'Wizard']),
            ('Spiritual Weapon', 2, 'Evo', 'BA', 'V/S', True, False, '1m', '60\'',
             ' ', ['Cleric']),
            ('Suggestion', 2, 'Ench', 'A', 'V/M', True, False, '8h', '30\'',
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Web', 2, 'Conj', 'A', 'V/S/M', True, False, '1h', '60\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Wither and Bloom', 2, 'Trans', 'A', 'V/S', True, False, '1m', '60\'',
             ' ', ['Druid']),

            # 3RD LEVEL SPELLS
            ('Animate Dead', 3, 'Necro', 'L', 'V/S/M', False, False, 'I', '10\'',
             ' ', ['Cleric', 'Wizard']),
            ('Aura of Vitality', 3, 'Evo', 'A', 'V', True, False, '1m', 'S',
             ' ', ['Paladin']),
            ('Beacon of Hope', 3, 'Abo', 'A', 'V/S', True, False, '1m', '30\'',
             ' ', ['Cleric']),
            ('Bestow Curse', 3, 'Ench', 'A', 'V/S', True, False, '1m', 'T',
             ' ', ['Bard', 'Cleric', 'Wizard']),
            ('Blinding Smite', 3, 'Evo', 'BA', 'V', True, False, '1m', 'S',
             ' ', ['Paladin']),
            ('Blink', 3, 'Trans', 'A', 'V/S', False, False, '1m', 'S',
             ' ', ['Sorcerer', 'Wizard']),
            ('Catnap', 3, 'Ench', 'A', 'S', False, False, '1m', '30\'',
             ' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Clairvoyance', 3, 'Div', 'L', 'V/S/M', True, False, '10m', '1 mile',
             ' ', ['Bard', 'Cleric', 'Sorcerer', 'Wizard']),
            ('Conjure Animals', 3, 'Conj', 'A', 'V/S', True, False, '1h', '60\'',
             ' ', ['Druid', 'Ranger']),
            ('Counterspell', 3, 'Abj', 'RA', 'V/S', False, False, 'I', '60\'',
             ' ', ['Sorcerer', 'Warlock', 'Wizard']),
            ('Create Food and Water', 3, 'Conj', 'A', 'V/S', False, False, 'I', '30\'',
             ' ', ['Cleric', 'Paladin']),
            ('Crusader\'s Mantle', 3, 'Evo', 'A', 'V', True, False, '1m', 'S',
             ' ', ['Paladin']),
            ('Daylight', 3, 'Evo', 'A', 'V/S/M', False, False, '1h', '60\'',
             ' ', ['Cleric', 'Druid', 'Paladin', 'Ranger', 'Sorcerer', 'Wizard']),
            ('Dispel Magic', 3, 'Abj', 'A', 'V/S', False, False, 'I', '120\'',
             ' ', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Elemental Weapon', 3, 'Trans', 'BA', 'V/S', True, False, '1h', 'T',
             ' ', ['Paladin', 'Ranger']),
            ('Enemies Abound', 3, 'Ench', 'A', 'V/S', True, False, '1m', '120\'',
             'For the spell\' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Erupting Earth', 3, 'Trans', 'A', 'V/S/M', False, False, 'I', '120\'',
             ' ', ['Druid', 'Sorcerer', 'Wizard']),
            ('Feign Death', 3, 'Necro', 'A', 'V/S', False, True, '1h', 'T',
             'You touch a corpse or other remains. For the duration, the body can\' ', ['Bard', 'Cleric', 'Druid', 'Wizard']),
            ('Fireball', 3, 'Evo', 'A', 'V/S/M', False, False, 'I', '150\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Fly', 3, 'Trans', 'A', 'V/S/M', True, False, '10m', 'T',
             ' ', ['Sorcerer', 'Wizard']),
            ('Glyph of Warding', 3, 'Abj', 'L', 'V/S/M', False, False, 'I', 'T',
             ' ', ['Bard', 'Cleric', 'Druid', 'Ranger', 'Sorcerer', 'Wizard']),
            ('Haste', 3, 'Trans', 'A', 'V/S/M', True, False, '1m', '30\'',
             'Choose a willing creature that you can see within range. Until the spell ends, the creature\' ', ['Sorcerer', 'Wizard']),
            ('Hunger of Hadar', 3, 'Conj', 'A', 'V/S/M', True, False, '1m', '150\'',
             ' ', ['Warlock']),
            ('Hypnotic Pattern', 3, 'Ill', 'A', 'V/S/M', True, False, '1m', '120\'',
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Intellect Fortress', 3, 'Abj', 'A', 'V', True, False, '1m', '30\'',
             'For the spell\' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Invisibility to Undead', 3, 'Abj', 'A', 'V/S/M', True, False, '1h', '60\'',
             'For the spell\' ', ['Cleric', 'Druid', 'Paladin', 'Ranger', 'Wizard']),
            ('Leomund\'s Tiny Hut', 3, 'Evo', 'L', 'V/S/M', False, True, '8h', 'S',
             ' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Lightning Bolt', 3, 'Evo', 'A', 'V/S/M', False, False, 'I', 'S',
             ' ', ['Sorcerer', 'Wizard']),
            ('Magic Circle', 3, 'Abj', 'L', 'V/S/M', False, False, '1h', '10\'',
             ' ', ['Bard', 'Cleric', 'Paladin', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Meld Into Stone', 3, 'Trans', 'A', 'V/S', False, True, '8h', 'T',
             ' ', ['Cleric', 'Druid', 'Ranger', 'Wizard']),
            ('Nondetection', 3, 'Abj', 'A', 'V/S/M', False, False, '8h', 'T',
             ' ', ['Bard', 'Ranger', 'Wizard']),
            ('Phantom Steed', 3, 'Ill', 'L', 'V/S', False, False, '1h', '30\'',
             ' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Revivify', 3, 'Evo', 'A', 'V/S/M', False, False, 'I', 'T',
             ' ', ['Cleric', 'Paladin']),
            ('Sending', 3, 'Evo', 'A', 'V/S/M', False, False, '1r', 'Unlimited',
             ' ', ['Bard', 'Cleric', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Sleet Storm', 3, 'Conj', 'A', 'V/S/M', True, False, '1m', '150\'',
             ' ', ['Druid', 'Sorcerer', 'Wizard']),
            ('Slow', 3, 'Trans', 'A', 'V/S/M', True, False, '1m', '120\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Speak with Dead', 3, 'Necro', 'L', 'V/S/M', False, False, '10m', '5\'',
             ' ', ['Bard', 'Cleric', 'Druid', 'Ranger', 'Wizard']),
            ('Stinking Cloud', 3, 'Conj', 'A', 'V/S/M', True, False, '1m', '90\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Summon Lesser Demon', 3, 'Conj', 'A', 'V/S/M', True, False, '1h', '30\'',
             'You utter foul words, summoning one demon from the chaos of the Abyss. You choose the demon\' ', ['Warlock', 'Wizard']),
            ('Summon Undead', 3, 'Necro', 'A', 'V/S/M', True, False, '1h', '10\'',
             ' ', ['Cleric', 'Warlock', 'Wizard']),
            ('Summon Construct', 3, 'Conj', 'A', 'V/S/M', True, False, '1h', '90\'',
             'You summon a construct in an unoccupied space that you can see within range. Choose the construct\' ', ['Artificer', 'Wizard']),
            ('Summon Fey', 3, 'Conj', 'A', 'V/S/M', True, False, '1h', '90\'',
             'You summon a fey creature in an unoccupied space that you can see within range. Choose the fey creature\' ', ['Bard', 'Druid', 'Ranger', 'Wizard']),
            ('Telekinesis', 3, 'Trans', 'A', 'V/S', True, False, '10m', '60\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Teleport', 3, 'Conj', 'A', 'V', False, False, 'I', '10\'',
             ' ', ['Sorcerer', 'Wizard', 'Warlock']),
            ('Tidal Wave', 3, 'Conj', 'A', 'V/S/M', False, False, 'I', '120\'',
             ' ', ['Druid', 'Sorcerer', 'Wizard']),
            ('Tiny Hut', 3, 'Evo', 'L', 'V/S/M', False, True, '8h', 'S',
             ' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Vampiric Touch', 3, 'Necro', 'A', 'V/S', True, False, '1m', 'S',
             ' ', ['Wizard']),
            ('Vortex Warp', 3, 'Trans', 'A', 'V/S', False, False, 'I', '90\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Wall of Sand', 3, 'Evo', 'A', 'V/S/M', True, False, '10m', '90\'',
             ' ', ['Druid', 'Sorcerer', 'Wizard']),
            ('Wall of Water', 3, 'Evo', 'A', 'V/S', True, False, '10m', '60\'',
             ' ', ['Druid', 'Sorcerer', 'Wizard']),
            ('Watery Sphere', 3, 'Conj', 'A', 'V/S/M', True, False, '1m', '90\'',
             ' ', ['Druid', 'Sorcerer', 'Wizard']),

            # 4TH LEVEL SPELLS
            ('Arcane Eye', 4, 'Div', 'A', 'V/S/M', True, False, '1h', '30\'',
             'For the spell\' ', ['Wizard', 'Bard']),
            ('Aura of Life', 4, 'Evo', 'A', 'V', True, False, '10m', 'S',
             ' ', ['Paladin']),
            ('Aura of Purity', 4, 'Evo', 'A', 'V', True, False, '10m', 'S',
             ' ', ['Paladin']),
            ('Banishment', 4, 'Abj', 'A', 'V/S/M', True, False, '1m', '60\'',
             ' ', ['Cleric', 'Paladin', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Blight', 4, 'Necro', 'A', 'V/S', False, False, 'I', '30\'',
             ' ', ['Druid', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Charm Monster', 4, 'Ench', 'A', 'V/S', True, False, '1h', '30\'',
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Confusion', 4, 'Ench', 'A', 'V/S/M', True, False, '1m', '90\'',
             ' ', ['Bard', 'Druid', 'Sorcerer', 'Wizard']),
            ('Conjure Minor Elementals', 4, 'Conj', 'A', 'V/S', True, False, '1h', '90\'',
             ' ', ['Druid', 'Wizard']),
            ('Control Water', 4, 'Trans', 'A', 'V/S/M', True, False, '10m', '300\'',
             ' ', ['Cleric', 'Druid', 'Wizard']),
            ('Dimension Door', 4, 'Conj', 'A', 'V', False, False, 'I', 'S',
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Divination', 4, 'Div', 'L', 'V/S/M', False, True, 'I', 'S',
             'Your magic and an offering put you in contact with a god or a god\' ', ['Cleric', 'Druid']),
            ('Elemental Bane', 4, 'Trans', 'A', 'V/S', True, False, '1m', '90\'',
             ' ', ['Druid', 'Warlock', 'Wizard']),
            ('Evard\'s Black Tentacles', 4, 'Conj', 'A', 'V/S/M', True, False, '1m', '90\'',
             ' ', ['Wizard']),
            ('Fire Shield', 4, 'Evo', 'A', 'V/S/M', False, False, '10m', 'S',
             'Thin and wispy flames wreathe your body for the spell\' ', ['Sorcerer', 'Wizard']),
            ('Foresight', 4, 'Div', 'L', 'V/S/M', False, False, '8h', 'T',
             ' ', ['Bard', 'Druid', 'Warlock', 'Wizard']),
            ('Freedom of Movement', 4, 'Abj', 'A', 'V/S/M', False, False, '1h', 'T',
             ' ', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Warlock']),
            ('Giant Insect', 4, 'Trans', 'A', 'V/S', True, False, '10m', '30\'',
             ' ', ['Druid']),
            ('Grasping Vine', 4, 'Conj', 'BA', 'V/S', True, False, '1m', '30\'',
             ' ', ['Druid', 'Ranger']),
            ('Greater Invisibility', 4, 'Ill', 'A', 'V/S', True, False, '1m', '30\'',
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Guardian of Faith', 4, 'Conj', 'A', 'V', False, False, '8h', '30\'',
             ' ', ['Cleric']),
            ('Hallucinatory Terrain', 4, 'Ill', 'L', 'V/S/M', False, False, '24h', '300\'',
             ' ', ['Bard', 'Druid', 'Ranger', 'Wizard']),
            ('Ice Storm', 4, 'Evo', 'A', 'V/S/M', False, False, 'I', '300\'',
             ' ', ['Druid', 'Sorcerer', 'Wizard']),
            ('Leomund\'s Secret Chest', 4, 'Conj', 'A', 'V/S/M', False, False, 'I', 'T',
             ' ', ['Wizard']),
            ('Locate Creature', 4, 'Div', 'A', 'V/S/M', True, False, '1h', 'S',
             'Describe or name a creature that is familiar to you. You sense the direction to the creature\' ', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Wizard']),
            ('Mordenkainen\'s Faithful Hound', 4, 'Conj', 'A', 'V/S/M', False, False, '8h', '30\'',
             ' ', ['Wizard']),
            ('Mordenkainen\'s Private Sanctum', 4, 'Abj', 'L', 'V/S/M', False, False, '24h', '120\'',
             ' ', ['Wizard']),
            ('Otiluke\'s Resilient Sphere', 4, 'Evo', 'A', 'V/S/M', False, False, '1m', '30\'',
             ' ', ['Wizard']),
            ('Phantasmal Killer', 4, 'Ill', 'A', 'V/S', True, False, '1m', '120\'',
             ' ', ['Wizard']),
            ('Polymorph', 4, 'Trans', 'A', 'V/S/M', True, False, '1h', '60\'',
             ' ', ['Bard', 'Druid', 'Sorcerer', 'Wizard']),
            ('Resilient Sphere', 4, 'Evo', 'A', 'V/S/M', False, False, '1m', '30\'',
             ' ', ['Wizard']),
            ('Shadow of Moil', 4, 'Evo', 'A', 'V/S', True, False, '1m', 'S',
             ' ', ['Warlock', 'Wizard']),
            ('Stone Shape', 4, 'Trans', 'A', 'V/S/M', False, False, 'I', 'T',
             ' ', ['Cleric', 'Druid', 'Ranger', 'Wizard']),
            ('Stoneskin', 4, 'Abj', 'A', 'V/S/M', True, False, '1h', 'T',
             ' ', ['Druid', 'Ranger', 'Sorcerer', 'Wizard']),
            ('Storm Sphere', 4, 'Evo', 'A', 'V/S/M', True, False, '1m', '150\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Summon Greater Demon', 4, 'Conj', 'A', 'V/S/M', True, False, '1h', '30\'',
             'You utter foul words, summoning one demon from the chaos of the Abyss. You choose the demon\' ', ['Warlock', 'Wizard']),
            ('Summon Elemental', 4, 'Conj', 'A', 'V/S/M', True, False, '1h', '90\'',
             ' ', ['Druid', 'Ranger', 'Wizard']),
            ('Terrain Surge', 4, 'Trans', 'A', 'V/S', False, False, 'I', '120\'',
             ' ', ['Druid', 'Sorcerer']),
            ('Vitriolic Sphere', 4, 'Evo', 'A', 'V/S/M', False, False, 'I', '150\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Wall of Fire', 4, 'Evo', 'A', 'V/S/M', True, False, '1m', '60\'',
             ' ', ['Druid', 'Sorcerer', 'Wizard']),
            ('Wall of Stone', 4, 'Evo', 'A', 'V/S/M', True, False, '10m', '120\'',
             ' ', ['Cleric', 'Druid', 'Ranger', 'Sorcerer', 'Wizard']),

            # 5TH LEVEL SPELLS
            ('Animate Objects', 5, 'Trans', 'A', 'V/S', True, False, '1m', '120\'',
             ' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Awaken', 5, 'Trans', 'L', 'V/S/M', False, False, 'I', 'T',
             ' ', ['Bard', 'Druid', 'Ranger']),
            ('Bigby\'s Hand', 5, 'Evo', 'A', 'V/S/M', True, False, '1m', '120\'',
             ' ', ['Wizard']),
            ('Cloudkill', 5, 'Conj', 'A', 'V/S', True, False, '10m', '120\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Commune', 5, 'Div', 'L', 'V/S/M', False, True, '1m', 'S',
             ' ', ['Cleric', 'Druid', 'Paladin']),
            ('Cone of Cold', 5, 'Evo', 'A', 'V/S/M', False, False, 'I', 'S',
             ' ', ['Sorcerer', 'Wizard']),
            ('Conjure Elemental', 5, 'Conj', 'A', 'V/S/M', True, False, '1h', '90\'',
             ' ', ['Druid', 'Ranger', 'Wizard']),
            ('Contact Other Plane', 5, 'Div', 'L', 'V', False, False, '1m', 'S',
             ' ', ['Warlock', 'Wizard']),
            ('Control Winds', 5, 'Trans', 'A', 'V/S', True, False, '1m', '300\'',
             ' ', ['Druid', 'Ranger', 'Sorcerer', 'Wizard']),
            ('Creation', 5, 'Ill', 'L', 'V/S/M', False, False, '24h', '30\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Delayed Blast Fireball', 5, 'Evo', 'A', 'V/S/M', True, False, '1m', '150\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Demiplane', 5, 'Conj', 'A', 'V/S/M', False, False, '1h', '60\'',
             ' ', ['Warlock', 'Wizard']),
            ('Destructive Wave', 5, 'Evo', 'A', 'V', False, False, 'I', 'S',
             ' ', ['Paladin']),
            ('Dispel Evil and Good', 5, 'Abj', 'A', 'V/S/M', True, False, '1m', 'S',
             'Shimmering energy springs from your outstretched hand. For the spell\' ', ['Cleric', 'Paladin']),
            ('Dominate Person', 5, 'Ench', 'A', 'V/S', True, False, '1m', '60\'',
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Dream', 5, 'Ill', 'L', 'V/S/M', False, False, '8h', 'Unlimited',
             'This spell shapes a creature\' ', ['Bard', 'Warlock', 'Wizard']),
            ('Flame Strike', 5, 'Evo', 'A', 'V/S/M', False, False, 'I', '60\'',
             ' ', ['Cleric', 'Paladin']),
            ('Geas', 5, 'Ench', 'A', 'V', True, False, '30d', '60\'',
             ' ', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Greater Restoration', 5, 'Abo', 'A', 'V/S/M', False, False, 'I', 'T',
             ' ', ['Bard', 'Cleric', 'Druid', 'Ranger']),
            ('Hallow', 5, 'Evo', 'L', 'V/S/M', False, False, 'I', 'T',
             ' ', ['Cleric', 'Druid', 'Paladin']),
            ('Hold Monster', 5, 'Ench', 'A', 'V/S/M', True, False, '1m', '90\'',
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Immolation', 5, 'Evo', 'A', 'V', True, False, '1m', '90\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Insect Plague', 5, 'Conj', 'A', 'V/S/M', True, False, '10m', '300\'',
             ' ', ['Cleric', 'Druid', 'Ranger', 'Sorcerer', 'Wizard']),
            ('Legend Lore', 5, 'Div', 'L', 'V/S/M', False, False, 'I', 'S',
             ' ', ['Bard', 'Cleric', 'Druid', 'Ranger', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Maelstrom', 5, 'Evo', 'A', 'V/S/M', True, False, '1m', '300\'',
             ' ', ['Druid', 'Ranger', 'Sorcerer']),
            ('Mass Cure Wounds', 5, 'Evo', 'A', 'V/S', False, False, 'I', '60\'',
             ' ', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger']),
            ('Mislead', 5, 'Ill', 'A', 'S', True, False, '1h', 'S',
             ' ', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Modify Memory', 5, 'Ench', 'A', 'V/S', True, False, '1m', '30\'',
             'You attempt to reshape another creature\' ', ['Bard', 'Cleric', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Mordenkainen\'s Magnificent Mansion', 5, 'Conj', 'L', 'V/S/M', False, False, '24h', '300\'',
             ' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Mordenkainen\'s Spell Immunity', 5, 'Abj', 'A', 'V/S/M', False, False, '8h', 'T',
             'For the spell\' ', ['Sorcerer', 'Warlock', 'Wizard']),
            ('Passwall', 5, 'Trans', 'A', 'V/S/M', False, False, '1h', '30\'',
             ' ', ['Wizard']),
            ('Planar Binding', 5, 'Abj', 'A', 'V/S/M', True, False, '1h', '60\'',
             ' ', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Raise Dead', 5, 'Necro', 'A', 'V/S/M', False, False, 'I', 'T',
             ' ', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger']),
            ('Reincarnate', 5, 'Trans', 'A', 'V/S/M', False, False, 'I', 'T',
             ' ', ['Druid', 'Ranger']),
            ('Scrying', 5, 'Div', 'L', 'V/S/M', True, False, '10m', 'Unlimited',
             ' ', ['Bard', 'Cleric', 'Druid', 'Ranger', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Seeming', 5, 'Ill', 'A', 'V/S/M', False, False, '8h', '30\'',
             ' ', ['Bard', 'Sorcerer', 'Wizard']),
            ('Telekinesis', 5, 'Trans', 'A', 'V/S', True, False, '10m', '60\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Teleportation Circle', 5, 'Conj', 'L', 'V/M', False, False, '1m', '10\'',
             ' ', ['Bard', 'Cleric', 'Druid', 'Ranger', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Tree Stride', 5, 'Conj', 'A', 'V/S', True, False, '1m', 'S',
             ' ', ['Druid', 'Ranger']),
            ('Tsunami', 5, 'Conj', 'A', 'V/S/M', True, False, '6 rounds', '500\'',
             ' ', ['Druid', 'Ranger', 'Sorcerer']),
            ('Wall of Conjuration', 5, 'Evo', 'A', 'V/S/M', True, False, '10m', '120\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Wall of Force', 5, 'Evo', 'A', 'V/S/M', True, False, '10m', '120\'',
             ' ', ['Sorcerer', 'Wizard']),
            ('Wish', 9, 'Conj', 'A', 'V', False, False, 'I', 'S',
             ' ', ['Sorcerer', 'Wizard', 'Warlock']),
        ]

        created_count = 0
        for spell_data in spells_data:
            name, level, category, casting_time, components, concentration, ritual, duration, range_str, description, spell_classes = spell_data
            
            spell, created = Spell.objects.get_or_create(
                name=name,
                defaults={
                    'level': level,
                    'category': category,
                    'casting_time': casting_time,
                    'components': components,
                    'requires_concentration': concentration,
                    'ritual': ritual,
                    'duration': duration,
                    'spell_range': range_str,
                    'description': description,
                }
            )
            
            if created:
                created_count += 1
                for class_name in spell_classes:
                    if class_name in class_objs:
                        spell.available_to_classes.add(class_objs[class_name])
                self.stdout.write(f"Created spell: {name}")

        self.stdout.write(self.style.SUCCESS(f"Successfully created {created_count} spells"))
