from django.core.management.base import BaseCommand
from base.models import Spell, SpellcastingClass

class Command(BaseCommand):
    help = 'Populate database with D&D 5e spells'

    def handle(self, *args, **options):
        # Create SpellcastingClass instances
        classes = [
            'Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 
            'Sorcerer', 'Warlock', 'Wizard'
        ]
        
        class_objs = {}
        for class_name in classes:
            obj, created = SpellcastingClass.objects.get_or_create(name=class_name)
            class_objs[class_name] = obj
            if created:
                self.stdout.write(f"Created class: {class_name}")

        # Parse and add spells
        spells_data = [
            # CANTRIPS (Level 0)
            ('Acid Splash', 0, 'Conj', 'A', 'V/S', False, False, 'I', '60\'',
             '1d6 acid damage against up to two adjacent targets, Dex saves.', ['Sorcerer', 'Wizard']),
            ('Blade Ward', 0, 'Abj', 'A', 'V/S', False, False, '1r', 'S', 
             'Resistance to bludgeoning, piercing, slashing until your next turn.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Chill Touch', 0, 'Necro', 'A', 'V/S', False, False, '1r', '120\'',
             'Target takes 1d8 necrotic damage and can\'t heal until your next turn.', ['Sorcerer', 'Warlock', 'Wizard']),
            ('Dancing Lights', 0, 'Evo', 'A', 'V/S/M', True, False, '1m', '120\'',
             'Creates four torch-sized lights, which illuminate 10\' and can be moved 60\' as a bonus action.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Druidcraft', 0, 'Trans', 'A', 'V/S', False, False, 'I', '30\'',
             'Cause one of several minor nature-related effects.', ['Druid']),
            ('Eldritch Blast', 0, 'Evo', 'A', 'V/S', False, False, 'I', '120\'',
             'Deals 1d10 force damage to target. More attacks at higher caster levels.', ['Warlock']),
            ('Fire Bolt', 0, 'Evo', 'A', 'V/S', False, False, 'I', '120\'',
             'Target takes 1d10 fire damage. Damage increases at higher caster levels.', ['Sorcerer', 'Wizard']),
            ('Friends', 0, 'Ench', 'A', 'S/M', True, False, '1m', 'S',
             'Grants advantage on Cha checks against target, but at the end, the creature knows you used magic on it and becomes hostile.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Guidance', 0, 'Div', 'A', 'V/S', True, False, '1m', 'T',
             'Target can roll 1d4 and add it to a single ability check.', ['Cleric', 'Druid']),
            ('Light', 0, 'Evo', 'A', 'V/M', False, False, '1h', 'T',
             'Object sheds 20\' of bright light and an additional 20\' of dim light.', ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Wizard']),
            ('Mage Hand', 0, 'Conj', 'A', 'V/S', False, False, '1m', '30\'',
             'Creates spectral hand that can lift 10lbs.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Mending', 0, 'Trans', 'L', 'V/S/M', False, False, 'I', 'T',
             'Repairs a single break or tear in the touched object.', ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Wizard']),
            ('Message', 0, 'Trans', 'A', 'V/S/M', False, False, '1r', '120\'',
             'Sends a whispered message to a target which only they can hear.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Minor Illusion', 0, 'Ill', 'A', 'S/M', False, False, '1m', '30\'',
             'Creates an auditory or visual hallucination.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Poison Spray', 0, 'Conj', 'A', 'V/S', False, False, 'I', '10\'',
             'Target takes 1d12 poison damage, Con save prevents.', ['Druid', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Prestidigitation', 0, 'Trans', 'A', 'V/S', False, False, 'Sp', '10\'',
             'Creates minor practical effects.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Produce Flames', 0, 'Conj', 'A', 'V/S', False, False, '10m', 'S',
             'Ranged spell attack within 30\' deals 1d8 fire damage.', ['Druid']),
            ('Ray of Frost', 0, 'Evo', 'A', 'V/S', False, False, 'I', '60\'',
             'Target takes 1d8 cold damage and loses 10\' of move speed for a turn.', ['Sorcerer', 'Wizard']),
            ('Resistance', 0, 'Abj', 'A', 'V/S/M', True, False, '1m', 'T',
             'Lets the target creature add +1d4 to a save.', ['Cleric', 'Druid']),
            ('Sacred Flame', 0, 'Evo', 'A', 'V/S', False, False, 'I', '60\'',
             '1d8 radiant damage, Dex save stops.', ['Cleric']),
            ('Shillelagh', 0, 'Trans', 'BA', 'V/S/M', False, False, '1m', 'T',
             'Held club or quarterstaff uses spellcasting ability.', ['Druid']),
            ('Shocking Grasp', 0, 'Evo', 'A', 'V/S', False, False, 'I', 'T',
             'Target takes 1d8 lightning damage, and can\'t take reactions.', ['Sorcerer', 'Wizard']),
            ('Spare the Dying', 0, 'Necro', 'A', 'V/S', False, False, 'I', 'T',
             'Target creature at 0 hp is stabilized.', ['Cleric']),
            ('Thaumaturgy', 0, 'Trans', 'A', 'V', False, False, '1m', '30\'',
             'Manifest a minor effect that is suggestive of supernatural power.', ['Cleric']),
            ('Thorn Whip', 0, 'Trans', 'A', 'V/S/M', False, False, 'I', '30\'',
             'Melee spell attack deals 1d6 piercing damage and pulls target.', ['Druid']),
            ('True Strike', 0, 'Div', 'A', 'S', True, False, '1r', '30\'',
             'Grants advantage on an attack roll against chosen creature next round.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Vicious Mockery', 0, 'Ench', 'A', 'V', False, False, 'I', '60\'',
             'Target takes 1d4 psychic and has disadvantage on next attack roll.', ['Bard']),

            # 1ST LEVEL SPELLS
            ('Alarm', 1, 'Abj', 'L', 'V/S/M', False, True, '8h', '30\'',
             'Sets an alarm which pings you if you\'re within a mile when something passes through the marked area.', ['Ranger', 'Wizard']),
            ('Animal Friendship', 1, 'Ench', 'A', 'V/S/M', False, False, '24h', '30\'',
             'Charms a beast with <3 Int for the day.', ['Bard', 'Druid', 'Ranger']),
            ('Armor of Agathys', 1, 'Abj', 'A', 'V/S/M', False, False, '1h', 'S',
             'You gain 5 temporary hit points, and whenever a creature hits you with a melee attack while you have temp HP remaining, the attacker takes 5 cold damage.', ['Warlock']),
            ('Bane', 1, 'Ench', 'A', 'V/S/M', True, False, '1m', '30\'',
             'Up to three creatures must make a Cha save or suffer a 1d4 penalty each time they attack or save.', ['Bard', 'Cleric']),
            ('Bless', 1, 'Ench', 'A', 'V/S/M', True, False, '1m', '30\'',
             'Target adds 1d4 to all attack rolls and saves.', ['Cleric', 'Paladin']),
            ('Burning Hands', 1, 'Evo', 'A', 'V/S', False, False, 'I', 'S',
             '3d6 fire damage to creatures in 15\' cone. Dex save halves damage.', ['Sorcerer', 'Wizard']),
            ('Charm Person', 1, 'Ench', 'A', 'V/S', False, False, '1h', '30\'',
             'Wis save or target is charmed.', ['Bard', 'Druid', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Color Spray', 1, 'Ill', 'A', 'V/S', False, False, 'I', 'S',
             'Spray of colors blinds, stuns, or knocks unconscious creatures in a 15\' cone.', ['Sorcerer', 'Wizard']),
            ('Command', 1, 'Ench', 'A', 'V', False, False, '1r', '60\'',
             'Issue a one word command. Wisdom save counters.', ['Cleric', 'Paladin']),
            ('Compelled Duel', 1, 'Ench', 'BA', 'V', True, False, '1m', '30\'',
             'Target must make Wis save or be compelled to fight you.', ['Paladin']),
            ('Comprehend Languages', 1, 'Div', 'A', 'V/S/M', False, True, '1h', 'S',
             'Allows you to understand any spoken or written language for an hour.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Cure Wounds', 1, 'Evo', 'A', 'V/S', False, False, 'I', 'T',
             'Heals 1d8 + (spellcasting ability modifier) damage.', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger']),
            ('Detect Evil or Good', 1, 'Div', 'A', 'V/S', True, False, '10m', 'S',
             'Recognizes aberration, celestial, fey, fiend, or undead within 30\'.', ['Cleric', 'Paladin']),
            ('Detect Magic', 1, 'Div', 'A', 'V/S', True, True, '10m', 'S',
             'Senses magical objects or creatures within 30\'.', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Detect Poison and Disease', 1, 'Div', 'A', 'V/S/M', True, True, '10m', 'S',
             'Senses poison, poisonous creatures, and disease within 30\'.', ['Cleric', 'Druid', 'Paladin', 'Ranger']),
            ('Disguise Self', 1, 'Ill', 'A', 'V/S', False, False, '1h', 'S',
             'Makes you and your armor look like another person.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Dissonant Whispers', 1, 'Ench', 'A', 'V', False, False, 'I', '60\'',
             '3d6 psychic damage, and target must use reaction to flee you.', ['Bard']),
            ('Divine Favor', 1, 'Evo', 'BA', 'V/S', True, False, '1m', 'S',
             'Weapon deals +1d4 radiant damage.', ['Paladin']),
            ('Ensnaring Strike', 1, 'Conj', 'BA', 'V', True, False, '1m', 'S',
             'When you next hit an opponent with your weapon, target is restrained by vines.', ['Ranger']),
            ('Faerie Fire', 1, 'Evo', 'A', 'V', True, False, '1m', '60\'',
             'Objects and people in a 20\' cube are lit up, counteracting invisibility.', ['Bard', 'Druid']),
            ('Feather Fall', 1, 'Trans', 'RA', 'V/M', False, False, '1m', '60\'',
             'Up to five falling creatures have their descent velocity capped at 60\'/round.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Find Familiar', 1, 'Conj', 'L', 'V/S/M', False, True, 'I', '10\'',
             'Gain a companion spirit in animal form to assist your magic.', ['Wizard', 'Warlock']),
            ('Fog Cloud', 1, 'Conj', 'A', 'V/S', True, False, '1h', '120\'',
             '20\' fog heavily obscures area.', ['Bard', 'Druid', 'Ranger', 'Sorcerer', 'Wizard']),
            ('Goodberry', 1, 'Trans', 'A', 'V/S/M', False, False, 'I', 'T',
             'Creates ten magic berries that each heal 1 hit point.', ['Druid', 'Ranger']),
            ('Guiding Bolt', 1, 'Evo', 'A', 'V/S', False, False, '1r', '120\'',
             'Ranged spell attack deals 4d6 radiant damage.', ['Cleric']),
            ('Hail of Thorns', 1, 'Conj', 'BA', 'V', True, False, '1m', 'S',
             'Around next creature struck with ranged weapon attack, deal 1d10 pierce to target and all within 5\'.', ['Ranger']),
            ('Healing Word', 1, 'Evo', 'BA', 'V', False, False, 'I', '60\'',
             'Creature regains 1d4 + (spellcasting ability mod) HP.', ['Bard', 'Cleric', 'Druid', 'Paladin']),
            ('Heroism', 1, 'Ench', 'A', 'V/S', True, False, '1m', 'T',
             'Creature gains immunity to being frightened and gains temporary hit points.', ['Bard', 'Paladin']),
            ('Hunter\'s Mark', 1, 'Div', 'BA', 'V', True, False, '1h', '90\'',
             'Marks target, granting +1d6 damage and advantage to Perception and Survival checks.', ['Ranger']),
            ('Identify', 1, 'Div', 'L', 'V/S/M*', False, True, 'I', 'T',
             'Identifies what a magical item does.', ['Bard', 'Wizard']),
            ('Jump', 1, 'Trans', 'A', 'V/S/M', False, False, '1m', 'T',
             'Triples target\'s jump distance.', ['Bard', 'Druid', 'Ranger', 'Sorcerer', 'Wizard']),
            ('Longstrider', 1, 'Trans', 'A', 'V/S/M', False, False, '1h', 'T',
             'Target\'s speed increases by +10\'.', ['Bard', 'Druid', 'Ranger', 'Wizard']),
            ('Magic Missile', 1, 'Evo', 'A', 'V/S', False, False, 'I', '120\'',
             'Shoot magic darts at one creature or several. Each deals 1d4 + 1 force damage.', ['Sorcerer', 'Wizard']),
            ('Protection from Evil and Good', 1, 'Abj', 'A', 'V/S/M', True, False, '10m', 'T',
             'Until the spell ends, one willing creature you touch is protected against certain creature types.', ['Cleric', 'Paladin', 'Warlock', 'Wizard']),
            ('Searing Smite', 1, 'Evo', 'BA', 'V', True, False, '1m', 'S',
             'Adds 1d6 fire damage to next melee weapon attack.', ['Paladin']),
            ('Shield', 1, 'Abj', 'RA', 'V/S', False, False, '1r', 'S',
             'Gain +5 AC including against the triggering attack.', ['Sorcerer', 'Wizard']),
            ('Shield of Faith', 1, 'Abj', 'BA', 'V/S/M', True, False, '10m', '60\'',
             'Grants +2 AC to target for duration.', ['Cleric', 'Paladin']),
            ('Silent Image', 1, 'Ill', 'A', 'V/S/M', True, False, '10m', '60\'',
             'Creates a visual illusion that you can move.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Sleep', 1, 'Ench', 'A', 'V/S/M', False, False, '1m', '90\'',
             '5d8 hit points of creatures are put to sleep.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Speak with Animals', 1, 'Div', 'A', 'V/S', False, True, '10m', 'S',
             'You can speak and verbally communicate with beasts for the duration.', ['Bard', 'Druid', 'Ranger']),
            ('Tasha\'s Hideous Laughter', 1, 'Ench', 'A', 'V/S/M', True, False, '1m', '60\'',
             'Target must succeed on Wis save or fall prone laughing.', ['Bard', 'Wizard']),
            ('Thunderous Smite', 1, 'Evo', 'BA', 'V', True, False, '1m', 'S',
             'Next attack deals 2d6 thunder damage to the target and pushes it 10\' away.', ['Paladin']),
            ('Thunderwave', 1, 'Evo', 'A', 'V/S', False, False, 'I', 'S',
             'Those within 15\' take 2d8 thunder damage and are pushed 10\' away.', ['Bard', 'Druid', 'Sorcerer', 'Wizard']),
            ('Wrathful Smite', 1, 'Evo', 'BA', 'V', True, False, '1m', 'S',
             'Next melee weapon attack deals 1d6 psychic damage.', ['Paladin']),

            # 2ND LEVEL SPELLS
            ('Acid Arrow', 2, 'Evo', 'A', 'V/S/M', False, False, 'I', '90\'',
             'Ranged spell attack deals 4d4 acid damage. At the end of the target\'s next turn, it takes 2d4 acid damage.', ['Wizard']),
            ('Aid', 2, 'Ench', 'A', 'V/S/M', False, False, '8h', '30\'',
             'For the duration, the target\'s hit point maximum and current hit points increase by 5.', ['Bard', 'Cleric', 'Paladin']),
            ('Alter Self', 2, 'Trans', 'A', 'V/S', True, False, '1h', 'S',
             'You assume a different form. When you cast the spell, choose one of the following options.', ['Sorcerer', 'Wizard']),
            ('Arcane Lock', 2, 'Abj', 'A', 'V/S/M', False, False, 'Sp', 'T',
             'You touch a closed door, window, gate, chest, or other closeable object. The object becomes locked if it isn\'t already.', ['Wizard']),
            ('Arcanist\'s Magic Aura', 2, 'Ill', 'A', 'V/S/M', False, False, '24h', 'T',
             'You place an illusion on a creature or an object you touch so that divination magic reveals false information.', ['Wizard', 'Bard']),
            ('Augury', 2, 'Div', 'A', 'V/S/M', False, True, 'I', 'S',
             'For this casting, you perceive the future as it branches along the path of the querent\'s immediate decision.', ['Cleric', 'Druid']),
            ('Barkskin', 2, 'Trans', 'A', 'V/S/M', True, False, '1h', 'T',
             'You touch a willing creature. Until the spell ends, the target\'s skin has a rough, bark-like appearance.', ['Druid', 'Ranger']),
            ('Beast Sense', 2, 'Div', 'A', 'V/S', True, True, '1h', 'T',
             'You touch a willing beast. For the duration of the spell, you can see through the beast\'s eyes and hear what it hears.', ['Druid', 'Ranger']),
            ('Blindness/Deafness', 2, 'Necro', 'A', 'V', True, False, '1m', '30\'',
             'For the spell\'s duration, the target is either blinded or deafened, as you choose.', ['Sorcerer', 'Wizard', 'Cleric']),
            ('Blur', 2, 'Ill', 'A', 'V', True, False, '1m', 'S',
             'Your body becomes blurred, shifting and wavering to all who can see you.', ['Sorcerer', 'Wizard']),
            ('Calm Emotions', 2, 'Ench', 'A', 'V/S', True, False, '1m', '60\'',
             'You attempt to suppress strong emotions in a group of people.', ['Bard', 'Cleric']),
            ('Continual Flame', 2, 'Evo', 'A', 'V/S/M', False, False, 'Sp', 'T',
             'A flame, equivalent in brightness to a torch, springs forth from an object that you touch.', ['Cleric', 'Wizard']),
            ('Darkness', 2, 'Evo', 'A', 'V/M', True, False, '10m', '60\'',
             'Magical darkness spreads from a point of your choice within range.', ['Sorcerer', 'Warlock', 'Wizard']),
            ('Darkvision', 2, 'Trans', 'A', 'V/S/M', False, False, '8h', 'T',
             'You touch a willing creature to grant it the ability to see in dim light within 60 feet as if it were bright light.', ['Druid', 'Ranger', 'Wizard']),
            ('Detect Thoughts', 2, 'Div', 'A', 'V/S/M', True, False, '1m', 'S',
             'For the spell\'s duration, you can sense the presence of thinking creatures within 30 feet of you.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Enhance Ability', 2, 'Trans', 'A', 'V/S/M', True, False, '1h', 'T',
             'You touch a creature and bestow upon it a magical enhancement. Choose one of the following effects.', ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Wizard']),
            ('Enthrall', 2, 'Ench', 'A', 'V/S', True, False, '1m', '60\'',
             'You weave a distracting string of words, causing creatures of your choice that you can see within 60 feet.', ['Bard', 'Warlock']),
            ('Find Traps', 2, 'Div', 'A', 'V/S', False, False, 'I', 'S',
             'You sense the presence of traps within 30 feet of you.', ['Cleric', 'Druid', 'Ranger', 'Wizard']),
            ('Flaming Sphere', 2, 'Conj', 'A', 'V/S/M', True, False, '1m', '60\'',
             'A 5-foot-diameter sphere of fire appears in an unoccupied space of your choice within range.', ['Druid', 'Sorcerer', 'Wizard']),
            ('Gentle Repose', 2, 'Necro', 'A', 'V/S/M', False, True, '10d', 'T',
             'You touch a corpse or other remains. For the duration, the body can\'t decay naturally.', ['Cleric', 'Wizard']),
            ('Gust of Wind', 2, 'Evo', 'A', 'V/S/M', True, False, '1m', 'S',
             'A line of strong wind 60 feet long and 10 feet wide blasts from you in a direction you choose for the spell\'s duration.', ['Druid', 'Sorcerer', 'Wizard']),
            ('Heat Metal', 2, 'Trans', 'A', 'V/S/M', True, False, '1m', '60\'',
             'Choose a manufactured metal object, such as a metal weapon or a suit of heavy or medium metal armor.', ['Bard', 'Druid']),
            ('Hold Person', 2, 'Ench', 'A', 'V/S/M', True, False, '1m', '60\'',
             'Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw.', ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Identify', 2, 'Div', 'L', 'V/S/M*', False, True, 'I', 'T',
             'Choose one object that you must touch throughout the casting of this spell.', ['Bard', 'Wizard']),
            ('Invisibility', 2, 'Ill', 'A', 'V/S/M', True, False, '1h', 'T',
             'A creature you touch becomes invisible until the spell ends.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Knock', 2, 'Trans', 'A', 'V', False, False, 'I', '60\'',
             'Choose an object that you can see within range. The object can be a door, box, chest, lock, or other object.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Lesser Restoration', 2, 'Abo', 'A', 'V/S', False, False, 'I', 'T',
             'You touch a creature and can end either one disease or one condition afflicting it.', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger']),
            ('Levitate', 2, 'Trans', 'A', 'V/S/M', True, False, '10m', '60\'',
             'One creature of your choice that you can see within range rises vertically, up to 20 feet.', ['Sorcerer', 'Wizard']),
            ('Locate Animals or Plants', 2, 'Div', 'A', 'V/S/M', False, True, 'I', 'S',
             'Describe or name a specific kind of beast or plant. Concentrating on the spell, you sense the direction and distance.', ['Bard', 'Druid', 'Ranger']),
            ('Locate Object', 2, 'Div', 'A', 'V/S/M', True, False, '10m', 'S',
             'Describe or name an object that is familiar to you. You sense the direction to the object\'s location.', ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Wizard']),
            ('Magic Mouth', 2, 'Ill', 'A', 'V/S/M', False, True, 'I', '30\'',
             'You implant a message within an object in range, a message that is uttered when a trigger occurs.', ['Bard', 'Wizard']),
            ('Magic Weapon', 2, 'Trans', 'BA', 'V/S', True, False, '1h', 'T',
             'You touch a nonmagical weapon. Until the spell ends, that weapon becomes a magic weapon with a +1 bonus.', ['Paladin', 'Wizard']),
            ('Melf\'s Acid Arrow', 2, 'Evo', 'A', 'V/S/M', False, False, 'I', '90\'',
             'A shimmering green arrow streaks toward a target within range.', ['Wizard', 'Sorcerer']),
            ('Mirror Image', 2, 'Ill', 'A', 'V/S', False, False, '1m', 'S',
             'Three illusory duplicates of yourself appear in your space.', ['Sorcerer', 'Warlock', 'Wizard']),
            ('Misty Step', 2, 'Conj', 'BA', 'V', False, False, 'I', 'S',
             'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Moonbeam', 2, 'Evo', 'A', 'V/S/M', True, False, '1m', '120\'',
             'A silvery beam of pale radiance springs from your hand into a cylinder 5 feet in radius.', ['Druid']),
            ('Pass Without Trace', 2, 'Trans', 'A', 'V/S/M', True, False, '1h', 'S',
             'A veil of shadows and silence radiates from you. For the duration, each creature of your choice.', ['Bard', 'Druid', 'Ranger']),
            ('Phantasmal Force', 2, 'Ill', 'A', 'V/S/M', True, False, '1m', '60\'',
             'You craft an illusory creature in the mind of a creature that you can see within range.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Prayer of Healing', 2, 'Evo', 'L', 'V', False, False, 'I', '30\'',
             'Up to six creatures of your choice that you can see within range each regain hit points.', ['Cleric', 'Druid']),
            ('Pyrotechnics', 2, 'Trans', 'A', 'V/S', False, False, 'I', '60\'',
             'Choose an area of nonmagical flame that you can see and that fits within a 5-foot cube within range.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Ray of Enfeeblement', 2, 'Necro', 'A', 'V/S', True, False, '1m', '60\'',
             'A black beam of enervating energy springs from your finger toward a creature within range.', ['Warlock', 'Wizard']),
            ('Rope Trick', 2, 'Trans', 'A', 'V/S/M', False, False, '1h', 'T',
             'You touch a length of rope 10 feet long. One end of the rope then rises into the air.', ['Wizard', 'Artificer']),
            ('Scorching Ray', 2, 'Evo', 'A', 'V/S', False, False, 'I', '120\'',
             'Each creature in a 5-foot-wide, 30-foot-long line originating from you takes 3d6 fire damage.', ['Sorcerer', 'Wizard']),
            ('See Invisibility', 2, 'Div', 'A', 'V/S/M', False, False, '1h', 'S',
             'For the spell\'s duration, you see invisible creatures and objects as if they were visible.', ['Sorcerer', 'Wizard', 'Bard']),
            ('Shatter', 2, 'Evo', 'A', 'V/S/M', False, False, 'I', '60\'',
             'A sudden loud ringing noise, painfully intense, erupts from a point of your choice within range.', ['Bard', 'Sorcerer', 'Wizard']),
            ('Silence', 2, 'Ill', 'A', 'V/S', True, False, '1m', '120\'',
             'For the duration, no sound can be created within or travel through a 20-foot-radius sphere centered on a point.', ['Bard', 'Cleric']),
            ('Spider Climb', 2, 'Trans', 'A', 'V/S/M', True, False, '1h', 'T',
             'Until the spell ends, one willing creature you touch gains the ability to move up, down, and across vertical surfaces.', ['Sorcerer', 'Warlock', 'Wizard']),
            ('Spiritual Weapon', 2, 'Evo', 'BA', 'V/S', True, False, '1m', '60\'',
             'You create a floating, spectral weapon within range that lasts for the duration of the spell.', ['Cleric']),
            ('Suggestion', 2, 'Ench', 'A', 'V/M', True, False, '8h', '30\'',
             'You suggest a course of activity, phrased in such a way as to make the activity sound reasonable.', ['Bard', 'Sorcerer', 'Warlock', 'Wizard']),
            ('Web', 2, 'Conj', 'A', 'V/S/M', True, False, '1h', '60\'',
             'You conjure a mass of thick, sticky webbing at a point of your choice within range.', ['Sorcerer', 'Wizard']),
            ('Wither and Bloom', 2, 'Trans', 'A', 'V/S', True, False, '1m', '60\'',
             'Choose a creature you can see within range. One creature of your choice within 30 feet of the target.', ['Druid']),
        ]

        created_count = 0
        for spell_data in spells_data:
            name, level, category, casting_time, components, concentration, ritual, duration, range_str, description, spell_classes = spell_data
            
            spell, created = Spell.objects.get_or_create(
                name=name,
                defaults={
                    'level': level,
                    'category': category,
                    'casting_time': casting_time,
                    'components': components,
                    'requires_concentration': concentration,
                    'ritual': ritual,
                    'duration': duration,
                    'spell_range': range_str,
                    'description': description,
                }
            )
            
            if created:
                created_count += 1
                for class_name in spell_classes:
                    if class_name in class_objs:
                        spell.available_to_classes.add(class_objs[class_name])
                self.stdout.write(f"Created spell: {name}")

        self.stdout.write(self.style.SUCCESS(f"Successfully created {created_count} spells"))
