# Generated by Django 6.0 on 2026-01-21 00:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Character Classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=0)),
                ('school', models.CharField(max_length=50)),
                ('cast_time', models.CharField(max_length=50)),
                ('components', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('range_area', models.CharField(max_length=100)),
                ('available_to_classes', models.ManyToManyField(related_name='spell_list', to='base.characterclass')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100)),
                ('subclass', models.CharField(max_length=100)),
                ('race', models.CharField(choices=[('Aasimar', 'Aasimar'), ('Human', 'Human'), ('Elf', 'Elf'), ('Dwarf', 'Dwarf'), ('Halfling', 'Halfling'), ('Gnome', 'Gnome'), ('Dragonborn', 'Dragonborn'), ('Tiefling', 'Tiefling'), ('Half-Elf', 'Half-Elf'), ('Half-Orc', 'Half-Orc'), ('Orc', 'Orc')], default='Human', max_length=30)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('background', models.CharField(choices=[('Acolyte', 'Acolyte'), ('Charlatan', 'Charlatan'), ('Criminal', 'Criminal'), ('Entertainer', 'Entertainer'), ('Folk Hero', 'Folk Hero'), ('Guild Artisan', 'Guild Artisan'), ('Hermit', 'Hermit'), ('Noble', 'Noble'), ('Outlander', 'Outlander'), ('Sage', 'Sage'), ('Sailor', 'Sailor'), ('Soldier', 'Soldier'), ('Urchin', 'Urchin'), ('Haunted One', 'Haunted One'), ('Urban Bounty Hunter', 'Urban Bounty Hunter'), ('Knight', 'Knight'), ('Faction Agent', 'Faction Agent'), ('Mercenary Veteran', 'Mercenary Veteran')], default='Acolyte', max_length=30)),
                ('alignment', models.CharField(choices=[('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LN', 'Lawful Neutral'), ('TN', 'True Neutral'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('CE', 'Chaotic Evil')], default='TN', max_length=2)),
                ('experience_points', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('strength', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('dexterity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('constitution', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('intelligence', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('wisdom', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('charisma', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('armor_class', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('initiative', models.IntegerField()),
                ('speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('hit_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('temporary_hit_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('hit_dice', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('death_saves_success', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('death_saves_failure', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('backstory', models.TextField(blank=True, null=True)),
                ('inspiration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='base.characterclass')),
                ('languages', models.ManyToManyField(blank=True, to='base.language')),
                ('spells', models.ManyToManyField(blank=True, related_name='learned_by_characters', to='base.spell')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 20)), name='level_range'), models.CheckConstraint(condition=models.Q(('experience_points__gte', 0)), name='experience_points_minimum'), models.CheckConstraint(condition=models.Q(('strength__gte', 1), ('strength__lte', 30)), name='strength_range'), models.CheckConstraint(condition=models.Q(('dexterity__gte', 1), ('dexterity__lte', 30)), name='dexterity_range'), models.CheckConstraint(condition=models.Q(('constitution__gte', 1), ('constitution__lte', 30)), name='constitution_range'), models.CheckConstraint(condition=models.Q(('intelligence__gte', 1), ('intelligence__lte', 30)), name='intelligence_range'), models.CheckConstraint(condition=models.Q(('wisdom__gte', 1), ('wisdom__lte', 30)), name='wisdom_range'), models.CheckConstraint(condition=models.Q(('charisma__gte', 1), ('charisma__lte', 30)), name='charisma_range'), models.CheckConstraint(condition=models.Q(('armor_class__gte', 1), ('armor_class__lte', 100)), name='armor_class_range'), models.CheckConstraint(condition=models.Q(('speed__gte', 1)), name='speed_minimum'), models.CheckConstraint(condition=models.Q(('hit_points__gte', 1)), name='hit_points_minimum'), models.CheckConstraint(condition=models.Q(('temporary_hit_points__gte', 0)), name='temporary_hit_points_minimum'), models.CheckConstraint(condition=models.Q(('hit_dice__gte', 1)), name='hit_dice_minimum'), models.CheckConstraint(condition=models.Q(('death_saves_success__gte', 0), ('death_saves_success__lte', 3)), name='death_saves_success_range'), models.CheckConstraint(condition=models.Q(('death_saves_failure__gte', 0), ('death_saves_failure__lte', 3)), name='death_saves_failure_range')],
            },
        ),
    ]
