# Generated by Django 6.0 on 2025-12-06 12:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100)),
                ('character_class', models.CharField(choices=[('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Fighter', 'Fighter'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], default='Fighter', max_length=20)),
                ('subclass', models.CharField(max_length=100)),
                ('race', models.CharField(choices=[('Aasimar', 'Aasimar'), ('Human', 'Human'), ('Elf', 'Elf'), ('Dwarf', 'Dwarf'), ('Halfling', 'Halfling'), ('Gnome', 'Gnome'), ('Dragonborn', 'Dragonborn'), ('Tiefling', 'Tiefling'), ('Half-Elf', 'Half-Elf'), ('Half-Orc', 'Half-Orc'), ('Orc', 'Orc')], default='Human', max_length=30)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('background', models.CharField(choices=[('Acolyte', 'Acolyte'), ('Charlatan', 'Charlatan'), ('Criminal', 'Criminal'), ('Entertainer', 'Entertainer'), ('Folk Hero', 'Folk Hero'), ('Guild Artisan', 'Guild Artisan'), ('Hermit', 'Hermit'), ('Noble', 'Noble'), ('Outlander', 'Outlander'), ('Sage', 'Sage'), ('Sailor', 'Sailor'), ('Soldier', 'Soldier'), ('Urchin', 'Urchin'), ('Haunted One', 'Haunted One'), ('Urban Bounty Hunter', 'Urban Bounty Hunter'), ('Knight', 'Knight'), ('Faction Agent', 'Faction Agent'), ('Mercenary Veteran', 'Mercenary Veteran')], default='Acolyte', max_length=30)),
                ('alignment', models.CharField(choices=[('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LN', 'Lawful Neutral'), ('TN', 'True Neutral'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('CE', 'Chaotic Evil')], default='TN', max_length=2)),
                ('experience_points', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('strength', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('dexterity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('constitution', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('intelligence', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('wisdom', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('charisma', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('armor_class', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('initiative', models.IntegerField()),
                ('speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('hit_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('temporary_hit_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('hit_dice', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('death_saves_success', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('death_saves_failure', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('backstory', models.TextField(blank=True, null=True)),
                ('inspiration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(blank=True, to='base.language')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 20)), name='level_range'), models.CheckConstraint(condition=models.Q(('experience_points__gte', 0)), name='experience_points_minimum'), models.CheckConstraint(condition=models.Q(('strength__gte', 1), ('strength__lte', 30)), name='strength_range'), models.CheckConstraint(condition=models.Q(('dexterity__gte', 1), ('dexterity__lte', 30)), name='dexterity_range'), models.CheckConstraint(condition=models.Q(('constitution__gte', 1), ('constitution__lte', 30)), name='constitution_range'), models.CheckConstraint(condition=models.Q(('intelligence__gte', 1), ('intelligence__lte', 30)), name='intelligence_range'), models.CheckConstraint(condition=models.Q(('wisdom__gte', 1), ('wisdom__lte', 30)), name='wisdom_range'), models.CheckConstraint(condition=models.Q(('charisma__gte', 1), ('charisma__lte', 30)), name='charisma_range'), models.CheckConstraint(condition=models.Q(('armor_class__gte', 1), ('armor_class__lte', 100)), name='armor_class_range'), models.CheckConstraint(condition=models.Q(('speed__gte', 1)), name='speed_minimum'), models.CheckConstraint(condition=models.Q(('hit_points__gte', 1)), name='hit_points_minimum'), models.CheckConstraint(condition=models.Q(('temporary_hit_points__gte', 0)), name='temporary_hit_points_minimum'), models.CheckConstraint(condition=models.Q(('hit_dice__gte', 1)), name='hit_dice_minimum'), models.CheckConstraint(condition=models.Q(('death_saves_success__gte', 0), ('death_saves_success__lte', 3)), name='death_saves_success_range'), models.CheckConstraint(condition=models.Q(('death_saves_failure__gte', 0), ('death_saves_failure__lte', 3)), name='death_saves_failure_range')],
            },
        ),
    ]
