# Generated by Django 6.0 on 2025-12-05 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100)),
                ('character_class', models.CharField(max_length=100)),
                ('subclass', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('background', models.CharField(max_length=100)),
                ('alligment', models.CharField(max_length=100)),
                ('experience_points', models.IntegerField(blank=True, null=True)),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('initiative', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('hit_points', models.IntegerField()),
                ('temporary_hit_points', models.IntegerField()),
                ('hit_dice', models.IntegerField()),
                ('death_saves_success', models.IntegerField(blank=True, null=True)),
                ('death_saves_failure', models.IntegerField(blank=True, null=True)),
                ('backstory', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
