# Generated by Django 6.0 on 2025-12-05 21:35

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='wisdom',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('strength__gte', 1), ('strength__lte', 30)), name='strength_range'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('dexterity__gte', 1), ('dexterity__lte', 30)), name='dexterity_range'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('constitution__gte', 1), ('constitution__lte', 30)), name='constitution_range'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('intelligence__gte', 1), ('intelligence__lte', 30)), name='intelligence_range'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('wisdom__gte', 1), ('wisdom__lte', 30)), name='wisdom_range'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('charisma__gte', 1), ('charisma__lte', 30)), name='charisma_range'),
        ),
    ]
