# Generated by Django 6.0 on 2026-01-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_populate_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='character',
            old_name='alligment',
            new_name='alignment',
        ),
        migrations.AlterField(
            model_name='character',
            name='subclass',
            field=models.CharField(blank=True, choices=[('thief', 'Thief'), ('assassin', 'Assassin'), ('trickster', 'Arcane Trickster'), ('champion', 'Champion'), ('battle_master', 'Battle Master'), ('life', 'Life Domain'), ('war', 'War Domain'), ('light', 'Light Domain'), ('none', 'None')], default='none', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('desc', models.TextField()),
                ('higher_level', models.TextField(blank=True, null=True)),
                ('page', models.CharField(max_length=50)),
                ('range', models.CharField(max_length=100)),
                ('components', models.CharField(max_length=255)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('ritual', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=100)),
                ('concentration', models.BooleanField(default=False)),
                ('casting_time', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('school', models.CharField(max_length=100)),
                ('dnd_classes', models.ManyToManyField(related_name='spells', to='base.characterclass')),
            ],
        ),
    ]
