# Generated by Django 6.0 on 2025-12-29 13:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_populate_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellcastingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Fighter', 'Fighter'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('category', models.CharField(choices=[('Abj', 'Abjuration'), ('Conj', 'Conjuration'), ('Div', 'Divination'), ('Ench', 'Enchantment'), ('Evo', 'Evocation'), ('Ill', 'Illusion'), ('Necro', 'Necromancy'), ('Trans', 'Transmutation')], max_length=10)),
                ('casting_time', models.CharField(choices=[('BA', 'Bonus Action'), ('RA', 'Reaction'), ('A', 'Action'), ('L', 'Long Cast Time (>1 round)')], max_length=2)),
                ('components', models.CharField(max_length=20)),
                ('requires_concentration', models.BooleanField(default=False)),
                ('ritual', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=50)),
                ('spell_range', models.CharField(db_column='range', max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_to_classes', models.ManyToManyField(blank=True, help_text='Classes that have access to this spell', to='base.spellcastingclass')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_prepared', models.BooleanField(default=True)),
                ('is_cast', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_spells', to='base.character')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.spell')),
            ],
            options={
                'ordering': ['spell__level', 'spell__name'],
                'unique_together': {('character', 'spell')},
            },
        ),
        migrations.AddIndex(
            model_name='spell',
            index=models.Index(fields=['level', 'category'], name='base_spell_level_d0c1ce_idx'),
        ),
    ]
