# Generated by Django 6.0.1 on 2026-01-16 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_populate_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stealth_bonus', models.PositiveIntegerField(default=5)),
                ('crit_chance', models.FloatField(default=0.05)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rogue_profile', to='base.character')),
            ],
            options={
                'verbose_name': 'Rogue',
            },
        ),
    ]
