# Generated by Django 6.0 on 2026-01-23 01:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_populate_languages"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="character",
            name="subclass",
        ),
        migrations.AlterField(
            model_name="character",
            name="character_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="characters",
                to="base.characterclass",
            ),
        ),
        migrations.CreateModel(
            name="ClassSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unlock_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.characterclass",
                    ),
                ),
            ],
            options={
                "ordering": ["unlock_level"],
            },
        ),
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("desc", models.TextField()),
                ("higher_level", models.TextField(blank=True, null=True)),
                ("page", models.CharField(max_length=50)),
                ("range", models.CharField(max_length=100)),
                ("components", models.CharField(max_length=255)),
                ("material", models.CharField(blank=True, max_length=255, null=True)),
                ("ritual", models.BooleanField(default=False)),
                ("duration", models.CharField(max_length=100)),
                ("concentration", models.BooleanField(default=False)),
                ("casting_time", models.CharField(max_length=100)),
                ("level", models.IntegerField()),
                ("school", models.CharField(max_length=100)),
                (
                    "dnd_classes",
                    models.ManyToManyField(
                        related_name="spells",
                        through="base.ClassSpell",
                        to="base.characterclass",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classspell",
            name="spell",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.spell"
            ),
        ),
        migrations.CreateModel(
            name="Subclass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subclasses",
                        to="base.characterclass",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classspell",
            name="subclass",
            field=models.ForeignKey(
                blank=True,
                help_text="Jeśli null → spell dostępny dla całej klasy",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.subclass",
            ),
        ),
        migrations.AddConstraint(
            model_name="classspell",
            constraint=models.UniqueConstraint(
                fields=("spell", "character_class", "subclass"),
                name="unique_spell_class_subclass",
            ),
        ),
    ]
