# Generated by Django 4.2 on 2026-01-12 15:00

from django.db import migrations, models
import django.db.models.deletion

def populate_character_classes(apps, schema_editor):
    Character = apps.get_model('base', 'Character')
    CharacterClass = apps.get_model('base', 'CharacterClass')
    
    # Get unique class names from the old char field
    class_names = Character.objects.values_list('character_class_old', flat=True).distinct()
    
    # Create CharacterClass instances
    for name in class_names:
        if name:
            CharacterClass.objects.get_or_create(name=name)

    # Link characters to the new CharacterClass instances
    for char_class in CharacterClass.objects.all():
        Character.objects.filter(character_class_old=char_class.name).update(character_class=char_class)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_populate_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Character Classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=0)),
                ('school', models.CharField(max_length=50)),
                ('cast_time', models.CharField(max_length=50)),
                ('components', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('range_area', models.CharField(max_length=100)),
                ('available_to_classes', models.ManyToManyField(related_name='spell_list', to='base.characterclass')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, related_name='learned_by_characters', to='base.spell'),
        ),
        migrations.RenameField(
            model_name='character',
            old_name='alligment',
            new_name='alignment',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='character_class',
            new_name='character_class_old',
        ),
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='base.characterclass'),
        ),
        migrations.RunPython(populate_character_classes),
        migrations.RemoveField(
            model_name='character',
            name='character_class_old',
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='base.characterclass'),
        ),
    ]
