# Generated by Django 6.0.1 on 2026-01-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rogue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rogue',
            options={},
        ),
        migrations.RemoveField(
            model_name='rogue',
            name='crit_chance',
        ),
        migrations.AddField(
            model_name='rogue',
            name='subclass_type',
            field=models.CharField(choices=[('thief', 'Thief'), ('assassin', 'Assassin'), ('trickster', 'Arcane Trickster')], default='thief', max_length=20),
        ),
        migrations.AlterField(
            model_name='rogue',
            name='stealth_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
