# Generated by Django 6.0 on 2025-12-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_spellcastingclass_spell_characterspell_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characterspell',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='characterspell',
            name='character',
        ),
        migrations.RemoveField(
            model_name='characterspell',
            name='spell',
        ),
        migrations.RemoveIndex(
            model_name='spell',
            name='base_spell_level_d0c1ce_idx',
        ),
        migrations.DeleteModel(
            name='CharacterSpell',
        ),
        migrations.DeleteModel(
            name='Spell',
        ),
        migrations.DeleteModel(
            name='SpellcastingClass',
        ),
    ]
