# Generated by Django 6.0 on 2026-01-20 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20260112_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('strength_increase', models.IntegerField(default=0)),
                ('dexterity_increase', models.IntegerField(default=0)),
                ('constitution_increase', models.IntegerField(default=0)),
                ('intelligence_increase', models.IntegerField(default=0)),
                ('wisdom_increase', models.IntegerField(default=0)),
                ('charisma_increase', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=30)),
                ('languages', models.ManyToManyField(blank=True, to='base.language')),
                ('traits', models.ManyToManyField(blank=True, to='base.trait')),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='base.race'),
        ),
        migrations.CreateModel(
            name='SubClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='base.characterclass')),
            ],
            options={
                'verbose_name_plural': 'Subclasses',
                'ordering': ['character_class', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='character',
            name='subclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.subclass'),
        ),
    ]
