# Generated by Django 6.0 on 2026-01-23 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_populate_classes_subclasses_spells'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='character',
            name='experience_points_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='strength_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='dexterity_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='constitution_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='intelligence_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='wisdom_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='charisma_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='armor_class_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='speed_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='hit_points_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='temporary_hit_points_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='hit_dice_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='death_saves_success_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='death_saves_failure_range',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='dnd_classes',
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, related_name='learned_by_characters', to='base.spell'),
        ),
        migrations.AddField(
            model_name='spell',
            name='available_to_classes',
            field=models.ManyToManyField(related_name='available_spells', through='base.ClassSpell', to='base.characterclass'),
        ),
        migrations.AlterField(
            model_name='classspell',
            name='subclass',
            field=models.ForeignKey(blank=True, help_text='If null -> spell available to the base class', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subclass'),
        ),
    ]
