# Generated by Gemini
from django.db import migrations

def populate_races_and_traits(apps, schema_editor):
    """
    Populates the database with core D&D races and their traits.
    """
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Race = apps.get_model('base', 'Race')
    Trait = apps.get_model('base', 'Trait')
    Language = apps.get_model('base', 'Language')

    # --- Traits ---
    traits_data = [
        {"name": "Breath Weapon", "description": "You can use your action to exhale destructive energy."},
        {"name": "Stonecunning", "description": "Whenever you make an Intelligence (History) check related to the origin of stonework, you are considered proficient in the History skill and add double your proficiency bonus to the check, instead of your normal proficiency bonus."},
        {"name": "Fey Ancestry", "description": "You have advantage on saving throws against being charmed, and magic can’t put you to sleep."},
        {"name": "Gnome Cunning", "description": "You have advantage on all Intelligence, Wisdom, and Charisma saving throws against magic."},
        {"name": "Relentless Endurance", "description": "When you are reduced to 0 hit points but not killed outright, you can drop to 1 hit point instead. You can’t use this feature again until you finish a long rest."},
        {"name": "Lucky", "description": "When you roll a 1 on an attack roll, ability check, or saving throw, you can reroll the die and must use the new roll."},
        {"name": "Hellish Resistance", "description": "You have resistance to fire damage."},
    ]

    for trait_info in traits_data:
        Trait.objects.get_or_create(**trait_info)

    # --- Languages ---
    # Ensure all necessary languages exist
    languages_to_ensure = [
        "Common", "Draconic", "Dwarvish", "Elven", "Gnomish", "Orc", "Halfling", "Infernal"
    ]
    for lang_name in languages_to_ensure:
        Language.objects.get_or_create(name=lang_name)


    # --- Races ---
    races_data = [
        {
            "name": "Dragonborn",
            "strength_increase": 2, "charisma_increase": 1, "wisdom_increase": 1, "speed": 30,
            "traits": ["Breath Weapon"],
            "languages": ["Common", "Draconic"]
        },
        {
            "name": "Dwarf",
            "constitution_increase": 2, "speed": 25,
            "traits": ["Stonecunning"],
            "languages": ["Common", "Dwarvish"]
        },
        {
            "name": "Elf",
            "dexterity_increase": 2, "intelligence_increase": 1, "speed": 30,
            "traits": ["Fey Ancestry"],
            "languages": ["Common", "Elven"]
        },
        {
            "name": "Gnome",
            "intelligence_increase": 2, "speed": 25,
            "traits": ["Gnome Cunning"],
            "languages": ["Common", "Gnomish"]
        },
        {
            "name": "Half-Elf",
            "charisma_increase": 2, "speed": 30,
            "traits": ["Fey Ancestry"],
            "languages": ["Common", "Elven"]
        },
        {
            "name": "Half-Orc",
            "strength_increase": 2, "constitution_increase": 1, "speed": 30,
            "traits": ["Relentless Endurance"],
            "languages": ["Common", "Orc"]
        },
        {
            "name": "Halfling",
            "dexterity_increase": 2, "charisma_increase": 1, "speed": 25,
            "traits": ["Lucky"],
            "languages": ["Common", "Halfling"]
        },
        {
            "name": "Human",
            "strength_increase": 1, "dexterity_increase": 1, "constitution_increase": 1,
            "intelligence_increase": 1, "wisdom_increase": 1, "charisma_increase": 1, "speed": 30,
            "traits": [],
            "languages": ["Common"]
        },
        {
            "name": "Tiefling",
            "charisma_increase": 2, "speed": 30,
            "traits": ["Hellish Resistance"],
            "languages": ["Common", "Infernal"]
        },
    ]

    for race_info in races_data:
        trait_names = race_info.pop("traits")
        language_names = race_info.pop("languages")
        
        race, created = Race.objects.get_or_create(**race_info)
        
        if created:
            for trait_name in trait_names:
                trait = Trait.objects.get(name=trait_name)
                race.traits.add(trait)
            
            for lang_name in language_names:
                language = Language.objects.get(name=lang_name)
                race.languages.add(language)


def delete_races_and_traits(apps, schema_editor):
    """
    Deletes the races and traits created in the forwards function.
    """
    Race = apps.get_model('base', 'Race')
    Trait = apps.get_model('base', 'Trait')
    
    # Simple deletion based on names. More robust would be to use IDs if they were static.
    trait_names = [
        "Breath Weapon", "Stonecunning", "Fey Ancestry", "Gnome Cunning", 
        "Relentless Endurance", "Lucky", "Hellish Resistance"
    ]
    race_names = [
        "Dragonborn", "Dwarf", "Elf", "Gnome", "Half-Elf", 
        "Half-Orc", "Halfling", "Human", "Tiefling"
    ]
    
    Trait.objects.filter(name__in=trait_names).delete()
    Race.objects.filter(name__in=race_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_trait_race_alter_character_race_subclass_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_races_and_traits, delete_races_and_traits),
    ]
