# Generated by Django 6.0 on 2025-12-29 14:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_characterspell_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellcastingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('category', models.CharField(choices=[('Abj', 'Abjuration'), ('Conj', 'Conjuration'), ('Div', 'Divination'), ('Ench', 'Enchantment'), ('Evo', 'Evocation'), ('Ill', 'Illusion'), ('Necro', 'Necromancy'), ('Trans', 'Transmutation')], max_length=10)),
                ('casting_time', models.CharField(max_length=50)),
                ('components', models.CharField(max_length=100)),
                ('requires_concentration', models.BooleanField(default=False)),
                ('ritual', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=50)),
                ('spell_range', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('available_to_classes', models.ManyToManyField(to='base.spellcastingclass')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_prepared', models.BooleanField(default=False)),
                ('is_cast_today', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_spells', to='base.character')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.spell')),
            ],
            options={
                'ordering': ['spell__level', 'spell__name'],
                'unique_together': {('character', 'spell')},
            },
        ),
    ]
