# Generated by Django 6.0 on 2025-12-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_character_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='character',
            name='strength_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='dexterity_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='constitution_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='intelligence_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='wisdom_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='charisma_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='level_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='armor_class_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='speed_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='hit_points_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='temporary_hit_points_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='hit_dice_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='death_saves_success_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='death_saves_failure_range',
        ),
    ]
