# Generated by Django 6.0.1 on 2026-01-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_rogue_options_remove_rogue_crit_chance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='subclass',
            field=models.CharField(choices=[('thief', 'Thief'), ('assassin', 'Assassin'), ('trickster', 'Arcane Trickster'), ('champion', 'Champion'), ('battle_master', 'Battle Master'), ('none', 'None')], default='none', max_length=30),
        ),
    ]
