# Generated by Django 6.0.1 on 2026-01-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_character_subclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='rogue',
            name='magic_item_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rogue',
            name='stealth_bonus',
            field=models.IntegerField(default=5),
        ),
    ]
