# Generated by Django 6.0 on 2026-01-23 09:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_item_character_subclass_inventoryitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("Aasimar", "Aasimar"),
                            ("Human", "Human"),
                            ("Elf", "Elf"),
                            ("Dwarf", "Dwarf"),
                            ("Halfling", "Halfling"),
                            ("Gnome", "Gnome"),
                            ("Dragonborn", "Dragonborn"),
                            ("Tiefling", "Tiefling"),
                            ("Half-Elf", "Half-Elf"),
                            ("Half-Orc", "Half-Orc"),
                            ("Orc", "Orc"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "ability",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("dexterity", "Dexterity"),
                            ("constitution", "Constitution"),
                            ("intelligence", "Intelligence"),
                            ("wisdom", "Wisdom"),
                            ("charisma", "Charisma"),
                        ],
                        max_length=20,
                    ),
                ),
                ("modifier", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="character",
            name="armor_class",
            field=models.IntegerField(
                blank=True,
                default=10,
                editable=False,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="subclass",
            field=models.ForeignKey(
                blank=True,
                help_text="Subclass of the character (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="characters",
                to="base.subclass",
            ),
        ),
    ]
