# Generated by Django 6.0 on 2025-12-05 22:00

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_character_strength_range_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='backstory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='death_saves_failure',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 20)), name='level_range'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('strength__gte', 1), ('strength__lte', 30)), name='strength_range'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('dexterity__gte', 1), ('dexterity__lte', 30)), name='dexterity_range'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('constitution__gte', 1), ('constitution__lte', 30)), name='constitution_range'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('intelligence__gte', 1), ('intelligence__lte', 30)), name='intelligence_range'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('wisdom__gte', 1), ('wisdom__lte', 30)), name='wisdom_range'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('charisma__gte', 1), ('charisma__lte', 30)), name='charisma_range'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('armor_class__gte', 1)), name='armor_class_minimum'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('speed__gte', 1)), name='speed_minimum'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('hit_points__gte', 1)), name='hit_points_minimum'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('temporary_hit_points__gte', 0)), name='temporary_hit_points_minimum'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('hit_dice__gte', 1)), name='hit_dice_minimum'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('death_saves_success__gte', 0), ('death_saves_success__lte', 3)), name='death_saves_success_range'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('death_saves_failure__gte', 0), ('death_saves_failure__lte', 3)), name='death_saves_failure_range'),
        ),
    ]
