# Generated by Django 6.0.1 on 2026-01-16 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rogue_magic_item_bonus_alter_rogue_stealth_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holy_symbol_bonus', models.IntegerField(default=2)),
                ('domain', models.CharField(choices=[('life', 'Life Domain'), ('war', 'War Domain'), ('light', 'Light Domain')], default='life', max_length=20)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleric_profile', to='base.character')),
            ],
        ),
    ]
