# Generated by Django 6.0.1 on 2026-01-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_cleric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='subclass',
            field=models.CharField(choices=[('thief', 'Thief'), ('assassin', 'Assassin'), ('trickster', 'Arcane Trickster'), ('champion', 'Champion'), ('battle_master', 'Battle Master'), ('life', 'Life Domain'), ('war', 'War Domain'), ('light', 'Light Domain'), ('none', 'None')], default='none', max_length=30),
        ),
    ]
