# Generated by Django 6.0.1 on 2026-01-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_character_subclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='subclass',
        ),
        migrations.RemoveField(
            model_name='cleric',
            name='holy_symbol_bonus',
        ),
        migrations.RemoveField(
            model_name='rogue',
            name='magic_item_bonus',
        ),
        migrations.RemoveField(
            model_name='rogue',
            name='stealth_bonus',
        ),
    ]
