# Generated by Django 6.0 on 2026-01-23 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_populate_equipment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Background",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(help_text="General description of the background"),
                ),
                (
                    "feature_name",
                    models.CharField(
                        help_text="Name of the background feature (e.g. Shelter of the Faithful)",
                        max_length=100,
                    ),
                ),
                (
                    "feature_description",
                    models.TextField(help_text="Rules text of the background feature"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="character",
            name="background",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="characters",
                to="base.background",
            ),
        ),
        migrations.CreateModel(
            name="BackgroundStartingEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "background",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starting_equipment",
                        to="base.background",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BackgroundSkillProficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "background",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.background",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.skill"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BackgroundToolProficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "background",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.background",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.tool"
                    ),
                ),
            ],
        ),
    ]
