# Generated by Django 6.0 on 2025-12-05 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_character_armor_class_minimum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='character',
            name='armor_class_range',
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('armor_class__gte', 1), ('armor_class__lte', 100)), name='armor_class_range'),
        ),
    ]
