# Generated by Django 6.0.1 on 2026-01-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_character_subclass_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='alligment',
            new_name='alignment',
        ),
    ]
