# Generated by Django 6.0.1 on 2026-01-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_alligment_character_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='subclass',
            field=models.CharField(blank=True, choices=[('thief', 'Thief'), ('assassin', 'Assassin'), ('trickster', 'Arcane Trickster'), ('champion', 'Champion'), ('battle_master', 'Battle Master'), ('life', 'Life Domain'), ('war', 'War Domain'), ('light', 'Light Domain'), ('none', 'None')], default='none', max_length=20, null=True),
        ),
    ]
