# Generated by Django 6.0 on 2025-12-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_character_armor_class_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='inspiration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='languages',
            field=models.ManyToManyField(blank=True, to='base.language'),
        ),
    ]
