# Generated by Django 6.0 on 2026-01-23 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_populate_backgrounds"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterclass",
            name="skill_choices_count",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="skill",
            name="ability",
            field=models.CharField(
                choices=[
                    ("strength", "Strength"),
                    ("dexterity", "Dexterity"),
                    ("constitution", "Constitution"),
                    ("intelligence", "Intelligence"),
                    ("wisdom", "Wisdom"),
                    ("charisma", "Charisma"),
                ],
                default="dexterity",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ClassSkillChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.characterclass",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.skill"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterSkillProficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.character"
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.skill"
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "skill")},
            },
        ),
    ]
