# Generated by Django 5.0.6 on 2024-05-23 16:00

from django.db import migrations, models

def populate_character_classes(apps, schema_editor):
    CharacterClass = apps.get_model('base', 'CharacterClass')
    class_choices = [
        'Barbarian', 'Bard', 'Cleric', 'Druid', 'Fighter', 'Monk',
        'Paladin', 'Ranger', 'Rogue', 'Sorcerer', 'Warlock', 'Wizard'
    ]
    for choice in class_choices:
        CharacterClass.objects.get_or_create(name=choice)

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_character_subclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('desc', models.TextField()),
                ('higher_level', models.TextField(blank=True, null=True)),
                ('page', models.CharField(max_length=50)),
                ('range', models.CharField(max_length=100)),
                ('components', models.CharField(max_length=255)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('ritual', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=100)),
                ('concentration', models.BooleanField(default=False)),
                ('casting_time', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('school', models.CharField(max_length=100)),
                ('dnd_classes', models.ManyToManyField(related_name='spells', to='base.CharacterClass')),
            ],
        ),
        migrations.RunPython(populate_character_classes),
    ]
