# Generated by Django 6.0 on 2025-12-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_language_character_inspiration_character_languages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
    ]
