# Generated by Django 6.0.1 on 2026-01-21 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_character_subclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='subclass',
            field=models.CharField(blank=True, choices=[('thief', 'Thief'), ('assassin', 'Assassin'), ('trickster', 'Arcane Trickster'), ('life', 'Life Domain'), ('war', 'War Domain'), ('light', 'Light Domain'), ('none', 'None'), ('champion', 'Champion'), ('battle_master', 'Battle Master'), ('eldritch_knight', 'Eldritch Knight'), ('devotion', 'Oath of Devotion'), ('ancients', 'Oath of the Ancients'), ('vengeance', 'Oath of Vengeance')], default='none', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subclass_type', models.CharField(choices=[('champion', 'Champion'), ('battle_master', 'Battle Master'), ('eldritch_knight', 'Eldritch Knight')], default='champion', max_length=20)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fighter_profile', to='base.character')),
            ],
        ),
        migrations.CreateModel(
            name='Paladin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subclass_type', models.CharField(choices=[('devotion', 'Oath of Devotion'), ('ancients', 'Oath of the Ancients'), ('vengeance', 'Oath of Vengeance')], default='devotion', max_length=20)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paladin_profile', to='base.character')),
            ],
        ),
    ]
