# Generated by Django 6.0.1 on 2026-01-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_populate_skill_abilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prerequisite', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='armor_class_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='speed_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='hit_points_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='temporary_hit_points_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='hit_dice_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='death_saves_success_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='death_saves_failure_range',
        ),
        migrations.AlterField(
            model_name='background',
            name='feature_name',
            field=models.CharField(help_text='Name of the background feature', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.CharField(choices=[('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LN', 'Lawful Neutral'), ('TN', 'True Neutral'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('CE', 'Chaotic Evil')], default='TN', max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='feats',
            field=models.ManyToManyField(blank=True, to='base.feat'),
        ),
    ]
