# Generated by Django 6.0 on 2026-01-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_populate_skill_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, related_name='learned_by_characters', to='base.spell'),
        ),
        migrations.AlterField(
            model_name='background',
            name='feature_name',
            field=models.CharField(help_text='Name of the background feature', max_length=100),
        ),
    ]
