# Generated by Django 6.0.1 on 2026-01-21 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_character_subclass_fighter_paladin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subclass_type', models.CharField(choices=[('lore', 'College of Lore'), ('valor', 'College of Valor'), ('glamour', 'College of Glamour')], default='lore', max_length=20)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bard_profile', to='base.character')),
            ],
        ),
        migrations.CreateModel(
            name='Ranger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subclass_type', models.CharField(choices=[('hunter', 'Hunter'), ('beast_master', 'Beast Master'), ('gloom_stalker', 'Gloom Stalker')], default='hunter', max_length=20)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranger_profile', to='base.character')),
            ],
        ),
    ]
