# Generated by Django 6.0 on 2026-01-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_populate_skill_abilities'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='character',
            name='experience_points_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='strength_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='dexterity_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='constitution_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='intelligence_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='wisdom_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='charisma_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='armor_class_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='speed_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='hit_points_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='temporary_hit_points_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='hit_dice_minimum',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='death_saves_success_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='death_saves_failure_range',
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, related_name='learned_by_characters', to='base.spell'),
        ),
        migrations.AlterField(
            model_name='background',
            name='feature_name',
            field=models.CharField(help_text='Name of the background feature', max_length=100),
        ),
    ]
