# Generated by Django 6.0 on 2026-01-27 23:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_character_spells_alter_background_feature_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "unlock_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_features",
                        to="base.characterclass",
                    ),
                ),
                (
                    "subclass",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = base class feature",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.subclass",
                    ),
                ),
            ],
            options={
                "ordering": ["unlock_level"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character_class", "subclass", "name"),
                        name="unique_class_feature",
                    )
                ],
            },
        ),
    ]
