# Generated by Django 6.0.1 on 2026-01-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_bard_ranger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='subclass',
            field=models.CharField(blank=True, choices=[('thief', 'Thief'), ('assassin', 'Assassin'), ('trickster', 'Arcane Trickster'), ('life', 'Life Domain'), ('war', 'War Domain'), ('light', 'Light Domain'), ('none', 'None'), ('champion', 'Champion'), ('battle_master', 'Battle Master'), ('eldritch_knight', 'Eldritch Knight'), ('devotion', 'Oath of Devotion'), ('ancients', 'Oath of the Ancients'), ('vengeance', 'Oath of Vengeance'), ('hunter', 'Hunter'), ('beast_master', 'Beast Master'), ('gloom_stalker', 'Gloom Stalker'), ('lore', 'College of Lore'), ('valor', 'College of Valor'), ('glamour', 'College of Glamour')], default='none', max_length=20, null=True),
        ),
    ]
