# Generated by Django 6.0.1 on 2026-01-23 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_feat_remove_character_armor_class_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='hit_dice',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_points',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='initiative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='temporary_hit_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
