# Generated by Django 6.0 on 2026-01-28 00:30

from django.db import migrations, models

def populate_races(apps, schema_editor):
    Race = apps.get_model('base', 'Race')

    races_data = [
        {
            "name": "Aasimar",
            "speed": 30,
            "features": "Darkvision: You have superior vision in dark and dim conditions.\nCelestial Resistance: You have resistance to necrotic damage and radiant damage.\nHealing Hands: As an action, you can touch a creature and cause it to regain a number of hit points equal to your level.\nLight Bearer: You know the light cantrip."
        },
        {
            "name": "Dragonborn",
            "speed": 30,
            "features": "Draconic Ancestry: You have draconic ancestry. Choose one type of dragon from the Draconic Ancestry table. Your breath weapon and damage resistance are determined by the dragon type.\nBreath Weapon: You can use your action to exhale destructive energy.\nDamage Resistance: You have resistance to the damage type associated with your draconic ancestry."
        },
        {
            "name": "Dwarf",
            "speed": 25,
            "features": "Darkvision: You have superior vision in dark and dim conditions.\nDwarven Resilience: You have advantage on saving throws against poison, and you have resistance against poison damage.\nDwarven Combat Training: You have proficiency with the battleaxe, handaxe, light hammer, and warhammer.\nTool Proficiency: You gain proficiency with the artisan’s tools of your choice: smith’s tools, brewer’s supplies, or mason’s tools."
        },
        {
            "name": "Elf",
            "speed": 30,
            "features": "Darkvision: Accustomed to twilit forests and the night sky, you have superior vision in dark and dim conditions.\nKeen Senses: You have proficiency in the Perception skill.\nFey Ancestry: You have advantage on saving throws against being charmed, and magic can’t put you to sleep.\nTrance: Elves don’t need to sleep. Instead, they meditate deeply for 4 hours a day."
        },
        {
            "name": "Gnome",
            "speed": 25,
            "features": "Darkvision: You have superior vision in dark and dim conditions.\nGnome Cunning: You have advantage on all Intelligence, Wisdom, and Charisma saving throws against magic."
        },
        {
            "name": "Half-Elf",
            "speed": 30,
            "features": "Darkvision: You have superior vision in dark and dim conditions.\nFey Ancestry: You have advantage on saving throws against being charmed, and magic can’t put you to sleep.\nSkill Versatility: You gain proficiency in two skills of your choice."
        },
        {
            "name": "Half-Orc",
            "speed": 30,
            "features": "Darkvision: You have superior vision in dark and dim conditions.\nMenacing: You gain proficiency in the Intimidation skill.\nRelentless Endurance: When you are reduced to 0 hit points but not killed outright, you can drop to 1 hit point instead. You can’t use this feature again until you finish a long rest.\nSavage Attacks: When you score a critical hit with a melee weapon attack, you can roll one of the weapon’s damage dice one additional time and add it to the extra damage of the critical hit."
        },
        {
            "name": "Halfling",
            "speed": 25,
            "features": "Lucky: When you roll a 1 on the d20 for an attack roll, ability check, or saving throw, you can reroll the die and must use the new roll.\nBrave: You have advantage on saving throws against being frightened.\nHalfling Nimbleness: You can move through the space of any creature that is of a size larger than yours."
        },
        {
            "name": "Human",
            "speed": 30,
            "features": "Ability Score Increase: Two different ability scores of your choice increase by 1.\nSkills: You gain proficiency in one skill of your choice.\nFeat: You gain one feat of your choice."
        },
        {
            "name": "Orc",
            "speed": 30,
            "features": "Adrenaline Rush: You can take the Dash action as a bonus action.\nDarkvision: You have superior vision in dark and dim conditions.\nPowerful Build: You count as one size larger when determining your carrying capacity and the weight you can push, drag, or lift."
        },
        {
            "name": "Tiefling",
            "speed": 30,
            "features": "Darkvision: You have superior vision in dark and dim conditions.\nHellish Resistance: You have resistance to fire damage.\nInfernal Legacy: You know the thaumaturgy cantrip. At 3rd level, you can cast the hellish rebuke spell as a 2nd-level spell once with this trait and regain the ability to do so when you finish a long rest. At 5th level, you can cast the darkness spell once with this trait and regain the ability to do so when you finish a long rest."
        }
    ]

    for race_info in races_data:
        Race.objects.update_or_create(
            name=race_info["name"],
            defaults={
                "speed": race_info["speed"],
                "racial_features": race_info["features"]
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_feat_race_characterclass_hit_die_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="speed",
            field=models.IntegerField(default=30),
        ),

        migrations.AddField(
            model_name="race",
            name="racial_features",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Opis cech rasowych, np. Darkvision, Resistances itp.",
            ),
        ),
        migrations.RunPython(populate_races, migrations.RunPython.noop),
    ]