# Generated by Django 6.0 on 2026-01-28 00:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_classfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('prerequisite', models.CharField(blank=True, help_text="e.g. 'Dexterity 13' or 'Elf'", max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('speed', models.IntegerField(default=30)),
            ],
        ),
        migrations.AddField(
            model_name='characterclass',
            name='hit_die',
            field=models.IntegerField(default=8, help_text='Hit die value, e.g., 8 for d8, 12 for d12'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='is_prepared_caster',
            field=models.BooleanField(default=False, help_text='If True, spells prepared limit = (Level * Multiplier) + Mod. If False, limit is taken from the progression table.'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='preparation_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for prepared spells formula. Wizard/Cleric = 1.0, Paladin = 0.5.'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='spellcasting_ability',
            field=models.CharField(blank=True, choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], help_text='Primary ability for spellcasting. Leave empty for non-casters.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='unarmored_bonus_ability',
            field=models.CharField(blank=True, choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], help_text='Ability that adds to AC when unarmored (e.g. Wisdom for Monk)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=30, editable=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='classspell',
            name='subclass',
            field=models.ForeignKey(blank=True, help_text='If null -> spell is available for the entire class', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subclass'),
        ),
        migrations.AddField(
            model_name='character',
            name='feats',
            field=models.ManyToManyField(blank=True, related_name='characters', to='base.feat'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.race'),
        ),
        migrations.CreateModel(
            name='ClassSpellProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('cantrips_known', models.IntegerField(default=0)),
                ('spells_known', models.IntegerField(default=0, help_text='Fixed known spells (Bard/Sorcerer). Set 0 for Prepared casters.')),
                ('slots_level_1', models.IntegerField(default=0)),
                ('slots_level_2', models.IntegerField(default=0)),
                ('slots_level_3', models.IntegerField(default=0)),
                ('slots_level_4', models.IntegerField(default=0)),
                ('slots_level_5', models.IntegerField(default=0)),
                ('slots_level_6', models.IntegerField(default=0)),
                ('slots_level_7', models.IntegerField(default=0)),
                ('slots_level_8', models.IntegerField(default=0)),
                ('slots_level_9', models.IntegerField(default=0)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_progression', to='base.characterclass')),
            ],
            options={
                'ordering': ['character_class', 'level'],
                'unique_together': {('character_class', 'level')},
            },
        ),
    ]
