# Generated by Django 6.0.1 on 2026-01-26 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_race_alter_character_speed_alter_character_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='base.race'),
            preserve_default=False,
        ),
    ]
