# Generated by Django 6.0 on 2025-12-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_character_character_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(choices=[('Acolyte', 'Acolyte'), ('Charlatan', 'Charlatan'), ('Criminal', 'Criminal'), ('Entertainer', 'Entertainer'), ('Folk Hero', 'Folk Hero'), ('Guild Artisan', 'Guild Artisan'), ('Hermit', 'Hermit'), ('Noble', 'Noble'), ('Outlander', 'Outlander'), ('Sage', 'Sage'), ('Sailor', 'Sailor'), ('Soldier', 'Soldier'), ('Urchin', 'Urchin'), ('Haunted One', 'Haunted One'), ('Urban Bounty Hunter', 'Urban Bounty Hunter'), ('Knight', 'Knight'), ('Faction Agent', 'Faction Agent'), ('Mercenary Veteran', 'Mercenary Veteran')], default='Acolyte', max_length=30),
        ),
    ]
