# Generated by Django 6.0 on 2026-01-28 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_feat_race_characterclass_hit_die_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclass',
            name='hit_die',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='is_prepared_caster',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='preparation_multiplier',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='skill_choices_count',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='spellcasting_ability',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='unarmored_bonus_ability',
        ),
    ]
