# Generated by Django 6.0 on 2026-01-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_populate_class_features"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="race",
            options={"ordering": ["name"]},
        ),
    ]
