# Generated by Django 6.0 on 2025-12-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_character_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='custom_race',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('Human', 'Human'), ('Elf', 'Elf'), ('Dwarf', 'Dwarf'), ('Halfling', 'Halfling'), ('Gnome', 'Gnome'), ('Dragonborn', 'Dragonborn'), ('Tiefling', 'Tiefling'), ('Half-Elf', 'Half-Elf'), ('Half-Orc', 'Half-Orc'), ('Orc', 'Orc'), ('Custom', 'Custom')], default='Human', max_length=30),
        ),
    ]
