# Generated by Django 6.0 on 2026-01-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_characterclass_hit_die_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='hit_die',
            field=models.IntegerField(default=8, help_text='Hit die value, e.g., 8 for d8, 12 for d12'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='is_prepared_caster',
            field=models.BooleanField(default=False, help_text='If True, spells prepared limit = (Level * Multiplier) + Mod. If False, limit is taken from the progression table.'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='preparation_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for prepared spells formula. Wizard/Cleric = 1.0, Paladin = 0.5.'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='skill_choices_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='spellcasting_ability',
            field=models.CharField(blank=True, choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], help_text='Primary ability for spellcasting. Leave empty for non-casters.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='unarmored_bonus_ability',
            field=models.CharField(blank=True, choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], help_text='Ability that adds to AC when unarmored (e.g. Wisdom for Monk)', max_length=20, null=True),
        ),
    ]
