# Generated by Django 6.0 on 2025-12-05 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_character_custom_race_alter_character_race'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='custom_race',
        ),
    ]
