# Generated by Django 6.0 on 2026-01-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_alter_race_options_alter_skill_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "prerequisite",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Dexterity 13' or 'Elf'",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="character",
            name="feats",
            field=models.ManyToManyField(
                blank=True, related_name="characters", to="base.feat"
            ),
        ),
    ]
