# Generated by Django 6.0 on 2026-01-28 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_characterclass_hit_die_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classfeature',
            options={},
        ),
        migrations.RemoveField(
            model_name='classfeature',
            name='unlock_level',
        ),
    ]
