# Generated by Django 6.0 on 2026-01-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_feat_alter_race_options_characterclass_hit_die_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RaceModifier',
        ),
    ]
