# Generated by Django 6.0 on 2026-01-26 20:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20260126_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('prerequisite', models.CharField(blank=True, help_text="e.g. 'Dexterity 13' or 'Elf'", max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='feats',
            field=models.ManyToManyField(blank=True, related_name='characters', to='base.feat'),
        ),
        migrations.CreateModel(
            name='ClassFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('level_unlocked', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='base.characterclass')),
                ('subclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='base.subclass')),
            ],
            options={
                'ordering': ['level_unlocked', 'name'],
                'unique_together': {('character_class', 'subclass', 'name')},
            },
        ),
    ]
