# Generated by Django 6.0 on 2025-12-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_character_custom_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('Human', 'Human'), ('Elf', 'Elf'), ('Dwarf', 'Dwarf'), ('Halfling', 'Halfling'), ('Gnome', 'Gnome'), ('Dragonborn', 'Dragonborn'), ('Tiefling', 'Tiefling'), ('Half-Elf', 'Half-Elf'), ('Half-Orc', 'Half-Orc'), ('Orc', 'Orc')], default='Human', max_length=30),
        ),
    ]
