# Generated by Django 6.0 on 2026-01-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_populate_feats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feat',
            name='prerequisite',
        ),
    ]
