# Generated by Django 6.0.1 on 2026-01-29 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_populate_feats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor_type', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], max_length=10)),
                ('base_ac', models.IntegerField()),
                ('adds_dex', models.BooleanField(default=True)),
                ('max_dex_bonus', models.IntegerField(blank=True, null=True)),
                ('str_requirement', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArmorClassBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_level', models.IntegerField(default=1)),
                ('flat_bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArmorClassFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_level', models.IntegerField(default=1)),
                ('base', models.IntegerField(default=10)),
                ('use_dex', models.BooleanField(default=True)),
                ('use_wis', models.BooleanField(default=False)),
                ('use_con', models.BooleanField(default=False)),
                ('use_int', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_bonus', models.IntegerField(default=2)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='armor_class_range',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='speed_minimum',
        ),
        migrations.AddField(
            model_name='armor',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='armor', to='base.item'),
        ),
        migrations.AddField(
            model_name='armorclassbonus',
            name='character_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.characterclass'),
        ),
        migrations.AddField(
            model_name='armorclassbonus',
            name='subclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subclass'),
        ),
        migrations.AddField(
            model_name='armorclassformula',
            name='character_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.characterclass'),
        ),
        migrations.AddField(
            model_name='armorclassformula',
            name='subclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subclass'),
        ),
        migrations.AddField(
            model_name='shield',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shield', to='base.item'),
        ),
        migrations.RemoveField(
            model_name='character',
            name='armor_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='speed',
        ),
    ]
