# Generated by Django 6.0 on 2026-01-28 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_classfeature_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classfeature',
            options={'ordering': ['unlock_level']},
        ),
        migrations.AddField(
            model_name='classfeature',
            name='unlock_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
    ]
